/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : AD0.h
**     Project   : Project
**     Processor : MC9S12XEP100MAG
**     Component : ADC
**     Version   : Component 01.630, Driver 01.19, CPU db: 3.00.036
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2016/8/16, 0:25
**     Abstract  :
**         This device "ADC" implements an A/D converter,
**         its control methods and interrupt/event handling procedure.
**     Settings  :
**          Component name                                 : AD0
**          A/D converter                                  : ADC0
**          Sharing                                        : Disabled
**          Interrupt service/event                        : Disabled
**          A/D channels                                   : 16
**            Channel0                                     : 
**              A/D channel (pin)                          : PAD00_AN00
**              A/D channel (pin) signal                   : AN00_KL15STAT
**            Channel1                                     : 
**              A/D channel (pin)                          : PAD01_AN01
**              A/D channel (pin) signal                   : AN01_5V3_AN
**            Channel2                                     : 
**              A/D channel (pin)                          : PAD02_AN02
**              A/D channel (pin) signal                   : AN02_5V1_AN
**            Channel3                                     : 
**              A/D channel (pin)                          : PAD03_AN03
**              A/D channel (pin) signal                   : AN03_START_AN
**            Channel4                                     : 
**              A/D channel (pin)                          : PAD04_AN04
**              A/D channel (pin) signal                   : AN04_M12A_IB2
**            Channel5                                     : 
**              A/D channel (pin)                          : PAD05_AN05
**              A/D channel (pin) signal                   : AN05_M12B_IB1
**            Channel6                                     : 
**              A/D channel (pin)                          : PAD06_AN06
**              A/D channel (pin) signal                   : AN06_IDID3_AN
**            Channel7                                     : 
**              A/D channel (pin)                          : PAD07_AN07
**              A/D channel (pin) signal                   : AN07_UBR_AN
**            Channel8                                     : 
**              A/D channel (pin)                          : PAD08_AN08
**              A/D channel (pin) signal                   : AN08_5V4_AN
**            Channel9                                     : 
**              A/D channel (pin)                          : PAD09_AN09
**              A/D channel (pin) signal                   : 
**            Channel10                                    : 
**              A/D channel (pin)                          : PAD10_AN10
**              A/D channel (pin) signal                   : 
**            Channel11                                    : 
**              A/D channel (pin)                          : PAD11_AN11
**              A/D channel (pin) signal                   : 
**            Channel12                                    : 
**              A/D channel (pin)                          : PAD12_AN12
**              A/D channel (pin) signal                   : 
**            Channel13                                    : 
**              A/D channel (pin)                          : PAD13_AN13
**              A/D channel (pin) signal                   : 
**            Channel14                                    : 
**              A/D channel (pin)                          : PAD14_AN14
**              A/D channel (pin) signal                   : 
**            Channel15                                    : 
**              A/D channel (pin)                          : PAD15_AN15
**              A/D channel (pin) signal                   : 
**          A/D resolution                                 : 12 bits
**          Conversion time                                : 1.600 µs
**          Sample time                                    : 4 clock periods
**          Discharge before sampling                      : Enabled
**          Result mode                                    : Right justified
**          Autoscan mode                                  : Disabled
**          AD conversions in STOP mode                    : Disabled
**          External trigger                               : Disabled
**          Internal trigger                               : Disabled
**          Number of conversions                          : 1
**          Initialization                                 : 
**            Enabled in init. code                        : yes
**            Events enabled in init.                      : yes
**          CPU clock/speed selection                      : 
**            High speed mode                              : This component enabled
**            Low speed mode                               : This component disabled
**            Slow speed mode                              : This component disabled
**          High input limit                               : 1
**          Low input limit                                : 0
**          Get value directly                             : yes
**          Wait for result                                : yes
**     Contents  :
**         MeasureChan  - byte AD0_MeasureChan(bool WaitForResult, byte Channel);
**         GetChanValue - byte AD0_GetChanValue(byte Channel, void* Value);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __AD0
#define __AD0

/* MODULE AD0. */

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

#pragma DATA_SEG AD0_DATA              /* Select data segment "AD0_DATA" */
#pragma CODE_SEG AD0_CODE

/* Constants for channel selection */
#define AD0_CHANNEL_AN00_KL15STAT       0U
#define AD0_CHANNEL_AN01_5V3_AN         1U
#define AD0_CHANNEL_AN02_5V1_AN         2U
#define AD0_CHANNEL_AN03_START_AN       3U
#define AD0_CHANNEL_AN04_M12A_IB2       4U
#define AD0_CHANNEL_AN05_M12B_IB1       5U
#define AD0_CHANNEL_AN06_IDID3_AN       6U
#define AD0_CHANNEL_AN07_UBR_AN         7U
#define AD0_CHANNEL_AN08_5V4_AN         8U


#define AD0_EnableTrigger AD0_EnableExtChanTrigger
/*
** ===================================================================
** The EnableTrigger method has been renamed to
** the EnableExtChanTrigger.
** This macro is here to keep project backward compatibility.
** ===================================================================
*/

#define AD0_DisableTrigger AD0_Stop
/*
** ===================================================================
** Now, the Stop method is used for disabling the trigger mode
** instead of the DisableTrigger.
** This macro is here to keep project backward compatibility.
** ===================================================================
*/


byte AD0_MeasureChan(bool WaitForResult,byte Channel);
/*
** ===================================================================
**     Method      :  AD0_MeasureChan (component ADC)
**
**     Description :
**         This method performs measurement on one channel. (Note: If
**         the <number of conversions> is more than one the conversion
**         of the A/D channel is performed specified number of times.)
**     Parameters  :
**         NAME            - DESCRIPTION
**         WaitForResult   - Wait for a result of
**                           conversion. If the <interrupt service> is
**                           disabled and at the same time a <number of
**                           conversions> is greater than 1, the
**                           WaitForResult parameter is ignored and the
**                           method waits for each result every time.
**         Channel         - Channel number. If only one
**                           channel in the component is set this
**                           parameter is ignored, because the parameter
**                           is set inside this method.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - Device is disabled
**                           ERR_BUSY - A conversion is already running
**                           ERR_RANGE - Parameter "Channel" out of range
** ===================================================================
*/

byte AD0_GetChanValue(byte Channel,void* Value);
/*
** ===================================================================
**     Method      :  AD0_GetChanValue (component ADC)
**
**     Description :
**         Returns the last measured value of the required channel.
**         Format and width of the value is a native format of the A/D
**         converter.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Channel         - Channel number. If only one
**                           channel in the component is set then this
**                           parameter is ignored.
**       * Value           - Pointer to the measured value. Data
**                           type is a byte, a word or an int. It
**                           depends on the supported modes, resolution,
**                           etc. of the AD converter. See the Version
**                           specific information for the current CPU in
**                           <General Info>.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_NOTAVAIL - Requested value not
**                           available
**                           ERR_RANGE - Parameter "Channel" out of
**                           range
**                           ERR_OVERRUN - External trigger overrun flag
**                           was detected after the last value(s) was
**                           obtained (for example by GetValue). This
**                           error may not be supported on some CPUs
**                           (see generated code).
** ===================================================================
*/

void AD0_Init(void);
/*
** ===================================================================
**     Method      :  AD0_Init (component ADC)
**
**     Description :
**         Initializes the associated peripheral(s) and the component's 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

#pragma DATA_SEG DEFAULT               /* Select data segment "DEFAULT" */
#pragma CODE_SEG DEFAULT

/* END AD0. */

#endif /* ifndef __AD0 */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
