/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : CAN1.c
**     Project   : Project
**     Processor : MC9S12XEP100MAG
**     Component : Init_MSCAN
**     Version   : Component 01.067, Driver 01.11, CPU db: 3.00.036
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2016/8/14, 15:02
**     Abstract  :
**          This file implements the MSCAN (MSCAN1) module initialization
**          according to the Peripheral Initialization Bean settings,
**          and defines interrupt service routines prototypes.
**          The Motorola Scalable Controller Area Network (MSCAN) definition
**          is based on the MSCAN12 definition which is the specific
**          implementation of the Motorola Scalable CAN concept targeted
**          for the Freescale MC68HC12 Microcontroller Family.
**
**          The basic features of the MSCAN are as follows:
**          - Implementation of the CAN protocol - Version 2.0A/B
**          – Standard and extended data frames
**          – 0 - 8 bytes data length
**          – Programmable bit rate up to 1 Mbps1
**          – Support for remote frames
**          – 5 receive buffers with FIFO storage scheme
**          - 3 transmit buffers with internal prioritization using a “local
**          priority concept
**          - Flexible maskable identifier filter supports two full size
**          extended identifier filters (two 32-bit) or four 16-bit filters
**          or eight 8-bit filters
**          - Programmable wake-up functionality with integrated low-pass
**          filter
**          - Programmable loop back mode supports self-test operation
**          - Programmable listen-only mode for monitoring of CAN bus
**          - Separate signalling and interrupt capabilities for all CAN
**          receiver and transmitter error states
**          (Warning, Error Passive, Bus-Off)
**          - Programmable MSCAN clock source either Bus Clock or Oscillator
**          Clock
**          - Internal timer for time-stamping of received and transmitted
**          messages
**          - Three low power modes: Sleep, Power Down and MSCAN Enable
**          - Global initialization of configuration registers
**     Settings  :
**          Bean name                                      : CAN1
**          Device                                         : MSCAN1
**          Clock Source                                   : Oscillator Clock
**          Baud Rate Prescaler                            : 2
**          Synchr. Jump Width                             : 3
**          Sampling                                       : One sample per bit
**          Time Segment 1                                 : 8
**          Time Segment 2                                 : 7
**          CAN frequency                                  : 8 MHz
**          Time quantum                                   : 125 ns
**          Bit rate                                       : 500 kbit/s
**          CAN Stops in Wait Mode                         : no
**          Wake-Up Mode                                   : None
**          Loop Back Test Mode                            : Disabled
**          Listen Only Mode                               : Normal operation
**          Sleep Mode Request                             : Disabled
**          Time Stamp                                     : Enabled
**          Acceptance mode                                : Two 32 bit Acceptance Filters
**          Rx acceptance ID(1st bank)                     : 00000000
**          Rx acceptance ID(2nd bank)                     : 00000000
**          Rx acceptance ID mask (1st bank)               : FFFFFFFF
**          Rx acceptance ID mask (2nd bank)               : FFFFFFFF
**          RXCAN pin                                      : PM2_RxCAN1_RxCAN0_MISO0
**          RXCAN pin signal                               : 
**          TXCAN pin                                      : PM3_TxCAN1_TxCAN0_SS0
**          TXCAN pin signal                               : 
**          Wake up                                        : 
**          Wake up                                        : Disabled
**          Interrupt                                      : Vcan1wkup
**          Wake interrupt priority                        : 4
**          ISR name                                       : 
**          Error                                          : 
**          Error Interrupt                                : Vcan1err
**          Status Change Interrupt                        : Disabled
**          Receiver Status Change                         : do not generate
**          Transmitt. Status Change                       : do not generate
**          Overrun Interrupt                              : Disabled
**          Error interrupt priority                       : 4
**          ISR name                                       : 
**          Receiver Full                                  : 
**          Receiver Full                                  : Enabled
**          Receiver Interrupt                             : Vcan1rx
**          Rx interrupt priority                          : 4
**          ISR name                                       : CAN1Rx
**          Transmitter empty                              : 
**          Transmitter Interrupt                          : Vcan1tx
**          Tx Empty Interrupt 0                           : Enabled
**          Tx Empty Interrupt 1                           : Disabled
**          Tx Empty Interrupt 2                           : Disabled
**          Tx interrupt priority                          : 4
**          ISR name                                       : CAN1Tx
**          Call Init in CPU init. code                    : yes
**          CAN Enable                                     : yes
**     Contents  :
**         Init - void CAN1_Init(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/* MODULE CAN1. */
#include "CAN1.h"

/*
** ###################################################################
**
**  The interrupt service routine(s) must be implemented
**  by user in one of the following user modules.
**
**  If the "Generate ISR" option is enabled, Processor Expert generates
**  ISR templates in the CPU event module.
**
**  User modules:
**      Project.c
**      Events.c
**
** ###################################################################
#pragma CODE_SEG __NEAR_SEG NON_BANKED
ISR(CAN1Rx)
        {
        // NOTE: The routine should include the following actions to obtain
        //       correct functionality of the hardware.
        //
        //      The ISR is invoked by RXF flag. The RXF flag is cleared
        //      if a "1" is written to the flag in CAN1RFLG register.
        //      Example: CAN1RFLG = CAN1RFLG_RXF_MASK;
        }
ISR(CAN1Tx)
        {
        // NOTE: The routine should include the following actions to obtain
        //       correct functionality of the hardware.
        //
        //       If you want to stop pending this interupt, corresponding enable bit
        //       must be cleared by writting "0". The interrupt must be enabled again before
        //       a next frame transmission start.
        //       Example: CAN1TIER_TXEIE0 = 0;
        //                CAN1TIER_TXEIE1 = 0;
        //                CAN1TIER_TXEIE2 = 0;
        //
        }
#pragma CODE_SEG DEFAULT
*/
/*
** ===================================================================
**     Method      :  CAN1_Init (component Init_MSCAN)
**
**     Description :
**         This method initializes registers of the CAN module
**         according to this Peripheral Initialization Bean settings.
**         Call this method in user code to initialize the module.
**         By default, the method is called by PE automatically; see
**         "Call Init method" property of the bean for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void CAN1_Init(void)
{
  /* CAN1RFLG: WUPIF=1,CSCIF=1,OVRIF=1,RXF=1 */
  setReg8Bits(CAN1RFLG, 0xC3U);         
  /* CAN1TFLG: TXE2=1,TXE1=1,TXE0=1 */
  setReg8Bits(CAN1TFLG, 0x07U);         

  /* CAN1CTL0: INITRQ=1 */
  setReg8Bits(CAN1CTL0, 0x01U);         
  while(CAN1CTL1_INITAK == 0U) {       /* Wait for init acknowledge */
  }
  /* CAN1CTL1: CANE=1,CLKSRC=0,LOOPB=0,LISTEN=0,BORM=0,WUPM=0,SLPAK=0,INITAK=1 */
  setReg8(CAN1CTL1, 0x81U);             
  /* CAN1BTR1: SAMP=0,TSEG22=1,TSEG21=1,TSEG20=0,TSEG13=0,TSEG12=1,TSEG11=1,TSEG10=1 */
  setReg8(CAN1BTR1, 0x67U);             
  /* CAN1BTR0: SJW1=1,SJW0=0,BRP5=0,BRP4=0,BRP3=0,BRP2=0,BRP1=0,BRP0=1 */
  setReg8(CAN1BTR0, 0x81U);             
  /* CAN1IDAC: ??=0,??=0,IDAM1=0,IDAM0=0,??=0,IDHIT2=0,IDHIT1=0,IDHIT0=0 */
  setReg8(CAN1IDAC, 0x00U);             
  /* CAN1IDAR0: AC7=0,AC6=0,AC5=0,AC4=0,AC3=0,AC2=0,AC1=0,AC0=0 */
  setReg8(CAN1IDAR0, 0x00U);            
  /* CAN1IDAR1: AC7=0,AC6=0,AC5=0,AC4=0,AC3=0,AC2=0,AC1=0,AC0=0 */
  setReg8(CAN1IDAR1, 0x00U);            
  /* CAN1IDAR2: AC7=0,AC6=0,AC5=0,AC4=0,AC3=0,AC2=0,AC1=0,AC0=0 */
  setReg8(CAN1IDAR2, 0x00U);            
  /* CAN1IDAR3: AC7=0,AC6=0,AC5=0,AC4=0,AC3=0,AC2=0,AC1=0,AC0=0 */
  setReg8(CAN1IDAR3, 0x00U);            
  /* CAN1IDAR4: AC7=0,AC6=0,AC5=0,AC4=0,AC3=0,AC2=0,AC1=0,AC0=0 */
  setReg8(CAN1IDAR4, 0x00U);            
  /* CAN1IDAR5: AC7=0,AC6=0,AC5=0,AC4=0,AC3=0,AC2=0,AC1=0,AC0=0 */
  setReg8(CAN1IDAR5, 0x00U);            
  /* CAN1IDAR6: AC7=0,AC6=0,AC5=0,AC4=0,AC3=0,AC2=0,AC1=0,AC0=0 */
  setReg8(CAN1IDAR6, 0x00U);            
  /* CAN1IDAR7: AC7=0,AC6=0,AC5=0,AC4=0,AC3=0,AC2=0,AC1=0,AC0=0 */
  setReg8(CAN1IDAR7, 0x00U);            
  /* CAN1IDMR0: AM7=1,AM6=1,AM5=1,AM4=1,AM3=1,AM2=1,AM1=1,AM0=1 */
  setReg8(CAN1IDMR0, 0xFFU);            
  /* CAN1IDMR1: AM7=1,AM6=1,AM5=1,AM4=1,AM3=1,AM2=1,AM1=1,AM0=1 */
  setReg8(CAN1IDMR1, 0xFFU);            
  /* CAN1IDMR2: AM7=1,AM6=1,AM5=1,AM4=1,AM3=1,AM2=1,AM1=1,AM0=1 */
  setReg8(CAN1IDMR2, 0xFFU);            
  /* CAN1IDMR3: AM7=1,AM6=1,AM5=1,AM4=1,AM3=1,AM2=1,AM1=1,AM0=1 */
  setReg8(CAN1IDMR3, 0xFFU);            
  /* CAN1IDMR4: AM7=1,AM6=1,AM5=1,AM4=1,AM3=1,AM2=1,AM1=1,AM0=1 */
  setReg8(CAN1IDMR4, 0xFFU);            
  /* CAN1IDMR5: AM7=1,AM6=1,AM5=1,AM4=1,AM3=1,AM2=1,AM1=1,AM0=1 */
  setReg8(CAN1IDMR5, 0xFFU);            
  /* CAN1IDMR6: AM7=1,AM6=1,AM5=1,AM4=1,AM3=1,AM2=1,AM1=1,AM0=1 */
  setReg8(CAN1IDMR6, 0xFFU);            
  /* CAN1IDMR7: AM7=1,AM6=1,AM5=1,AM4=1,AM3=1,AM2=1,AM1=1,AM0=1 */
  setReg8(CAN1IDMR7, 0xFFU);            
  /* CAN1CTL0: INITRQ=0 */
  clrReg8Bits(CAN1CTL0, 0x01U);         
  while(CAN1CTL1_INITAK) {             /* Wait for init exit */
  }
  /* CAN1CTL0: RXFRM=0,RXACT=0,CSWAI=0,SYNCH=0,TIME=1,WUPE=0,SLPRQ=0,INITRQ=0 */
  setReg8(CAN1CTL0, 0x08U);             
  /* CAN1RIER: WUPIE=0,CSCIE=0,RSTATE1=0,RSTATE0=0,TSTATE1=0,TSTATE0=0,OVRIE=0,RXFIE=1 */
  setReg8(CAN1RIER, 0x01U);             
  /* CAN1TIER: ??=0,??=0,??=0,??=0,??=0,TXEIE2=0,TXEIE1=0,TXEIE0=1 */
  setReg8(CAN1TIER, 0x01U);             
}

/* END CAN1. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
