/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Cpu.c
**     Project   : Project
**     Processor : MC9S12XEP100MAG
**     Component : MC9S12XEP100_144
**     Version   : Component 01.003, Driver 02.06, CPU db: 3.00.034
**     Datasheet : MC9S12XEP100 Rev. 1.19 12/2008
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2017/5/31, 19:04
**     Abstract  :
**         This component "MC9S12XEP100_144" implements properties, methods,
**         and events of the CPU.
**     Settings  :
**
**     Contents  :
**         EnableInt   - void Cpu_EnableInt(void);
**         DisableInt  - void Cpu_DisableInt(void);
**         SetWaitMode - void Cpu_SetWaitMode(void);
**         SetStopMode - void Cpu_SetStopMode(void);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE Cpu. */

#include "AD0.h"
#include "AD1.h"
#include "GPIOA.h"
#include "GPIOB.h"
#include "GPIOC.h"
#include "GPIOD.h"
#include "GPIOE.h"
#include "GPIOH.h"
#include "GPIOJ.h"
#include "GPIOK.h"
#include "GPIOS.h"
#include "ECT.h"
#include "SPI2.h"
#include "Wdg.h"
#include "CAN0.h"
#include "CAN1.h"
#include "TickTimer.h"
#include "TimeStamp.h"
#include "PWM0.h"
#include "PWM1.h"
#include "PWM2.h"
#include "PWM3.h"
#include "PWM4.h"
#include "PWM5.h"
#include "PWM6.h"
#include "PWM7.h"
#include "Flash.h"
#include "EEPROM.h"
#include "CAN2.h"
#include "CAN3.h"
#include "Events.h"
#include "Cpu.h"

#define CGM_DELAY  0x13FFU

#pragma DATA_SEG DEFAULT               /* Select data segment "DEFAULT" */
#pragma CODE_SEG DEFAULT


/* Global variables */
volatile byte CCR_reg;                 /* Current CCR reegister */
#pragma CODE_SEG __NEAR_SEG NON_BANKED


/*
** ===================================================================
**     Method      :  Cpu_Cpu_Interrupt (component MC9S12XEP100_144)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(Cpu_Interrupt)
{
  /*lint -save -e950 Disable MISRA rule (1.1) checking. */
  asm(BGND);
  /*lint -restore Enable MISRA rule (1.1) checking. */
}


#pragma CODE_SEG DEFAULT

/*
** ===================================================================
**     Method      :  Cpu_DisableInt (component MC9S12XEP100_144)
**
**     Description :
**         Disable maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_DisableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_EnableInt (component MC9S12XEP100_144)
**
**     Description :
**         Enable maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_EnableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_SetStopMode (component MC9S12XEP100_144)
**
**     Description :
**         Set low power mode - Stop mode.
**         For more information about the stop mode see
**         documentation of this CPU.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_SetStopMode(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_SetWaitMode (component MC9S12XEP100_144)
**
**     Description :
**         Set low power mode - Wait mode.
**         For more information about the wait mode see
**         documentation of this CPU.
**         Release from Wait mode: Reset or interrupt
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_SetWaitMode(void)

**      This method is implemented as macro in the header module. **
*/

#pragma OPTION ADD "-Onf"              /* Disable 'Create Sub-Functions with Common Code optimalization' */
/*
** ===================================================================
**     Method      :  PE_low_level_init (component MC9S12XEP100_144)
**
**     Description :
**         Initializes components and provides common register 
**         initialization. The method is called automatically as a part 
**         of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void PE_low_level_init(void)
{
  /* Int. priority initialization */
  /*                                        No. Address Pri XGATE Name            Description */
  setReg8(INT_CFADDR, 0x70U);           
  setReg8(INT_CFDATA3, 0x04U);         /*  0x3B  0xFF76   4   no   ivVpit2         used by PE */ 
  setReg8(INT_CFDATA4, 0x04U);         /*  0x3C  0xFF78   4   no   ivVpit1         used by PE */ 
  setReg8(INT_CFDATA7, 0x04U);         /*  0x3F  0xFF7E   4   no   ivVapi          used by PE */ 
  setReg8(INT_CFADDR, 0x90U);           
  setReg8(INT_CFDATA4, 0x04U);         /*  0x4C  0xFF98   4   no   ivVcan3tx       used by PE */ 
  setReg8(INT_CFDATA5, 0x04U);         /*  0x4D  0xFF9A   4   no   ivVcan3rx       used by PE */ 
  setReg8(INT_CFADDR, 0xA0U);           
  setReg8(INT_CFDATA0, 0x04U);         /*  0x50  0xFFA0   4   no   ivVcan2tx       used by PE */ 
  setReg8(INT_CFDATA1, 0x04U);         /*  0x51  0xFFA2   4   no   ivVcan2rx       used by PE */ 
  setReg8(INT_CFDATA4, 0x04U);         /*  0x54  0xFFA8   4   no   ivVcan1tx       used by PE */ 
  setReg8(INT_CFDATA5, 0x04U);         /*  0x55  0xFFAA   4   no   ivVcan1rx       used by PE */ 
  setReg8(INT_CFADDR, 0xB0U);           
  setReg8(INT_CFDATA0, 0x04U);         /*  0x58  0xFFB0   4   no   ivVcan0tx       used by PE */ 
  setReg8(INT_CFDATA1, 0x04U);         /*  0x59  0xFFB2   4   no   ivVcan0rx       used by PE */ 
  setReg8(INT_CFDATA2, 0x04U);         /*  0x5A  0xFFB4   4   no   ivVcan0err      used by PE */ 
  setReg8(INT_CFADDR, 0xC0U);           
  setReg8(INT_CFDATA6, 0x04U);         /*  0x66  0xFFCC   4   no   ivVporth        used by PE */ 
  setReg8(INT_CFDATA7, 0x04U);         /*  0x67  0xFFCE   4   no   ivVportj        used by PE */ 
  setReg8(INT_CFADDR, 0xD0U);           
  setReg8(INT_CFDATA7, 0x04U);         /*  0x6F  0xFFDE   4   no   ivVectovf       used by PE */ 
  setReg8(INT_CFADDR, 0xE0U);           
  setReg8(INT_CFDATA0, 0x04U);         /*  0x70  0xFFE0   4   no   ivVectch7       used by PE */ 
  setReg8(INT_CFDATA1, 0x04U);         /*  0x71  0xFFE2   4   no   ivVectch6       used by PE */ 
  setReg8(INT_CFDATA2, 0x04U);         /*  0x72  0xFFE4   4   no   ivVectch5       used by PE */ 
  setReg8(INT_CFDATA3, 0x04U);         /*  0x73  0xFFE6   4   no   ivVectch4       used by PE */ 
  setReg8(INT_CFDATA4, 0x04U);         /*  0x74  0xFFE8   4   no   ivVectch3       used by PE */ 
  setReg8(INT_CFDATA5, 0x04U);         /*  0x75  0xFFEA   4   no   ivVectch2       used by PE */ 
  setReg8(INT_CFDATA6, 0x04U);         /*  0x76  0xFFEC   4   no   ivVectch1       used by PE */ 
  setReg8(INT_CFDATA7, 0x04U);         /*  0x77  0xFFEE   4   no   ivVectch0       used by PE */ 
  /* Initialization of Memory Protection unit */
  /* MPUSEL: SVSEN=0,??=0,??=0,??=0,??=0,SEL=1 */
  setReg8(MPUSEL, 0x01U);              /* Select Descriptor num. 1 */ 
  /* MPUDESC2: LOW_ADDR10=0,LOW_ADDR9=0,LOW_ADDR8=0,LOW_ADDR7=0,LOW_ADDR6=0,LOW_ADDR5=0,LOW_ADDR4=0,LOW_ADDR3=0 */
  setReg8(MPUDESC2, 0x00U);             
  /* MPUDESC1: LOW_ADDR18=0,LOW_ADDR17=0,LOW_ADDR16=0,LOW_ADDR15=0,LOW_ADDR14=0,LOW_ADDR13=0,LOW_ADDR12=0,LOW_ADDR11=0 */
  setReg8(MPUDESC1, 0x00U);             
  /* MPUDESC0: MSTR0=0,MSTR1=0,MSTR2=0,MSTR3=0,LOW_ADDR22=0,LOW_ADDR21=0,LOW_ADDR20=0,LOW_ADDR19=0 */
  setReg8(MPUDESC0, 0x00U);             
  /* MPUDESC5: HIGH_ADDR10=1,HIGH_ADDR9=1,HIGH_ADDR8=1,HIGH_ADDR7=1,HIGH_ADDR6=1,HIGH_ADDR5=1,HIGH_ADDR4=1,HIGH_ADDR3=1 */
  setReg8(MPUDESC5, 0xFFU);             
  /* MPUDESC4: HIGH_ADDR18=1,HIGH_ADDR17=1,HIGH_ADDR16=1,HIGH_ADDR15=1,HIGH_ADDR14=1,HIGH_ADDR13=1,HIGH_ADDR12=1,HIGH_ADDR11=1 */
  setReg8(MPUDESC4, 0xFFU);             
  /* MPUDESC3: WP=0,NEX=0,??=0,??=0,HIGH_ADDR22=1,HIGH_ADDR21=1,HIGH_ADDR20=1,HIGH_ADDR19=1 */
  setReg8(MPUDESC3, 0x0FU);             
  /* MPUSEL: SVSEN=0,??=0,??=0,??=0,??=0,SEL=2 */
  setReg8(MPUSEL, 0x02U);              /* Select Descriptor num. 2 */ 
  /* MPUDESC2: LOW_ADDR10=0,LOW_ADDR9=0,LOW_ADDR8=0,LOW_ADDR7=0,LOW_ADDR6=0,LOW_ADDR5=0,LOW_ADDR4=0,LOW_ADDR3=0 */
  setReg8(MPUDESC2, 0x00U);             
  /* MPUDESC1: LOW_ADDR18=0,LOW_ADDR17=0,LOW_ADDR16=0,LOW_ADDR15=0,LOW_ADDR14=0,LOW_ADDR13=0,LOW_ADDR12=0,LOW_ADDR11=0 */
  setReg8(MPUDESC1, 0x00U);             
  /* MPUDESC0: MSTR0=0,MSTR1=0,MSTR2=0,MSTR3=0,LOW_ADDR22=0,LOW_ADDR21=0,LOW_ADDR20=0,LOW_ADDR19=0 */
  setReg8(MPUDESC0, 0x00U);             
  /* MPUDESC5: HIGH_ADDR10=1,HIGH_ADDR9=1,HIGH_ADDR8=1,HIGH_ADDR7=1,HIGH_ADDR6=1,HIGH_ADDR5=1,HIGH_ADDR4=1,HIGH_ADDR3=1 */
  setReg8(MPUDESC5, 0xFFU);             
  /* MPUDESC4: HIGH_ADDR18=1,HIGH_ADDR17=1,HIGH_ADDR16=1,HIGH_ADDR15=1,HIGH_ADDR14=1,HIGH_ADDR13=1,HIGH_ADDR12=1,HIGH_ADDR11=1 */
  setReg8(MPUDESC4, 0xFFU);             
  /* MPUDESC3: WP=0,NEX=0,??=0,??=0,HIGH_ADDR22=1,HIGH_ADDR21=1,HIGH_ADDR20=1,HIGH_ADDR19=1 */
  setReg8(MPUDESC3, 0x0FU);             
  /* MPUSEL: SVSEN=0,??=0,??=0,??=0,??=0,SEL=3 */
  setReg8(MPUSEL, 0x03U);              /* Select Descriptor num. 3 */ 
  /* MPUDESC2: LOW_ADDR10=0,LOW_ADDR9=0,LOW_ADDR8=0,LOW_ADDR7=0,LOW_ADDR6=0,LOW_ADDR5=0,LOW_ADDR4=0,LOW_ADDR3=0 */
  setReg8(MPUDESC2, 0x00U);             
  /* MPUDESC1: LOW_ADDR18=0,LOW_ADDR17=0,LOW_ADDR16=0,LOW_ADDR15=0,LOW_ADDR14=0,LOW_ADDR13=0,LOW_ADDR12=0,LOW_ADDR11=0 */
  setReg8(MPUDESC1, 0x00U);             
  /* MPUDESC0: MSTR0=0,MSTR1=0,MSTR2=0,MSTR3=0,LOW_ADDR22=0,LOW_ADDR21=0,LOW_ADDR20=0,LOW_ADDR19=0 */
  setReg8(MPUDESC0, 0x00U);             
  /* MPUDESC5: HIGH_ADDR10=1,HIGH_ADDR9=1,HIGH_ADDR8=1,HIGH_ADDR7=1,HIGH_ADDR6=1,HIGH_ADDR5=1,HIGH_ADDR4=1,HIGH_ADDR3=1 */
  setReg8(MPUDESC5, 0xFFU);             
  /* MPUDESC4: HIGH_ADDR18=1,HIGH_ADDR17=1,HIGH_ADDR16=1,HIGH_ADDR15=1,HIGH_ADDR14=1,HIGH_ADDR13=1,HIGH_ADDR12=1,HIGH_ADDR11=1 */
  setReg8(MPUDESC4, 0xFFU);             
  /* MPUDESC3: WP=0,NEX=0,??=0,??=0,HIGH_ADDR22=1,HIGH_ADDR21=1,HIGH_ADDR20=1,HIGH_ADDR19=1 */
  setReg8(MPUDESC3, 0x0FU);             
  /* MPUSEL: SVSEN=0,??=0,??=0,??=0,??=0,SEL=4 */
  setReg8(MPUSEL, 0x04U);              /* Select Descriptor num. 4 */ 
  /* MPUDESC2: LOW_ADDR10=0,LOW_ADDR9=0,LOW_ADDR8=0,LOW_ADDR7=0,LOW_ADDR6=0,LOW_ADDR5=0,LOW_ADDR4=0,LOW_ADDR3=0 */
  setReg8(MPUDESC2, 0x00U);             
  /* MPUDESC1: LOW_ADDR18=0,LOW_ADDR17=0,LOW_ADDR16=0,LOW_ADDR15=0,LOW_ADDR14=0,LOW_ADDR13=0,LOW_ADDR12=0,LOW_ADDR11=0 */
  setReg8(MPUDESC1, 0x00U);             
  /* MPUDESC0: MSTR0=0,MSTR1=0,MSTR2=0,MSTR3=0,LOW_ADDR22=0,LOW_ADDR21=0,LOW_ADDR20=0,LOW_ADDR19=0 */
  setReg8(MPUDESC0, 0x00U);             
  /* MPUDESC5: HIGH_ADDR10=1,HIGH_ADDR9=1,HIGH_ADDR8=1,HIGH_ADDR7=1,HIGH_ADDR6=1,HIGH_ADDR5=1,HIGH_ADDR4=1,HIGH_ADDR3=1 */
  setReg8(MPUDESC5, 0xFFU);             
  /* MPUDESC4: HIGH_ADDR18=1,HIGH_ADDR17=1,HIGH_ADDR16=1,HIGH_ADDR15=1,HIGH_ADDR14=1,HIGH_ADDR13=1,HIGH_ADDR12=1,HIGH_ADDR11=1 */
  setReg8(MPUDESC4, 0xFFU);             
  /* MPUDESC3: WP=0,NEX=0,??=0,??=0,HIGH_ADDR22=1,HIGH_ADDR21=1,HIGH_ADDR20=1,HIGH_ADDR19=1 */
  setReg8(MPUDESC3, 0x0FU);             
  /* MPUSEL: SVSEN=0,??=0,??=0,??=0,??=0,SEL=5 */
  setReg8(MPUSEL, 0x05U);              /* Select Descriptor num. 5 */ 
  /* MPUDESC2: LOW_ADDR10=0,LOW_ADDR9=0,LOW_ADDR8=0,LOW_ADDR7=0,LOW_ADDR6=0,LOW_ADDR5=0,LOW_ADDR4=0,LOW_ADDR3=0 */
  setReg8(MPUDESC2, 0x00U);             
  /* MPUDESC1: LOW_ADDR18=0,LOW_ADDR17=0,LOW_ADDR16=0,LOW_ADDR15=0,LOW_ADDR14=0,LOW_ADDR13=0,LOW_ADDR12=0,LOW_ADDR11=0 */
  setReg8(MPUDESC1, 0x00U);             
  /* MPUDESC0: MSTR0=0,MSTR1=0,MSTR2=0,MSTR3=0,LOW_ADDR22=0,LOW_ADDR21=0,LOW_ADDR20=0,LOW_ADDR19=0 */
  setReg8(MPUDESC0, 0x00U);             
  /* MPUDESC5: HIGH_ADDR10=1,HIGH_ADDR9=1,HIGH_ADDR8=1,HIGH_ADDR7=1,HIGH_ADDR6=1,HIGH_ADDR5=1,HIGH_ADDR4=1,HIGH_ADDR3=1 */
  setReg8(MPUDESC5, 0xFFU);             
  /* MPUDESC4: HIGH_ADDR18=1,HIGH_ADDR17=1,HIGH_ADDR16=1,HIGH_ADDR15=1,HIGH_ADDR14=1,HIGH_ADDR13=1,HIGH_ADDR12=1,HIGH_ADDR11=1 */
  setReg8(MPUDESC4, 0xFFU);             
  /* MPUDESC3: WP=0,NEX=0,??=0,??=0,HIGH_ADDR22=1,HIGH_ADDR21=1,HIGH_ADDR20=1,HIGH_ADDR19=1 */
  setReg8(MPUDESC3, 0x0FU);             
  /* MPUSEL: SVSEN=0,??=0,??=0,??=0,??=0,SEL=6 */
  setReg8(MPUSEL, 0x06U);              /* Select Descriptor num. 6 */ 
  /* MPUDESC2: LOW_ADDR10=0,LOW_ADDR9=0,LOW_ADDR8=0,LOW_ADDR7=0,LOW_ADDR6=0,LOW_ADDR5=0,LOW_ADDR4=0,LOW_ADDR3=0 */
  setReg8(MPUDESC2, 0x00U);             
  /* MPUDESC1: LOW_ADDR18=0,LOW_ADDR17=0,LOW_ADDR16=0,LOW_ADDR15=0,LOW_ADDR14=0,LOW_ADDR13=0,LOW_ADDR12=0,LOW_ADDR11=0 */
  setReg8(MPUDESC1, 0x00U);             
  /* MPUDESC0: MSTR0=0,MSTR1=0,MSTR2=0,MSTR3=0,LOW_ADDR22=0,LOW_ADDR21=0,LOW_ADDR20=0,LOW_ADDR19=0 */
  setReg8(MPUDESC0, 0x00U);             
  /* MPUDESC5: HIGH_ADDR10=1,HIGH_ADDR9=1,HIGH_ADDR8=1,HIGH_ADDR7=1,HIGH_ADDR6=1,HIGH_ADDR5=1,HIGH_ADDR4=1,HIGH_ADDR3=1 */
  setReg8(MPUDESC5, 0xFFU);             
  /* MPUDESC4: HIGH_ADDR18=1,HIGH_ADDR17=1,HIGH_ADDR16=1,HIGH_ADDR15=1,HIGH_ADDR14=1,HIGH_ADDR13=1,HIGH_ADDR12=1,HIGH_ADDR11=1 */
  setReg8(MPUDESC4, 0xFFU);             
  /* MPUDESC3: WP=0,NEX=0,??=0,??=0,HIGH_ADDR22=1,HIGH_ADDR21=1,HIGH_ADDR20=1,HIGH_ADDR19=1 */
  setReg8(MPUDESC3, 0x0FU);             
  /* MPUSEL: SVSEN=0,??=0,??=0,??=0,??=0,SEL=7 */
  setReg8(MPUSEL, 0x07U);              /* Select Descriptor num. 7 */ 
  /* MPUDESC2: LOW_ADDR10=0,LOW_ADDR9=0,LOW_ADDR8=0,LOW_ADDR7=0,LOW_ADDR6=0,LOW_ADDR5=0,LOW_ADDR4=0,LOW_ADDR3=0 */
  setReg8(MPUDESC2, 0x00U);             
  /* MPUDESC1: LOW_ADDR18=0,LOW_ADDR17=0,LOW_ADDR16=0,LOW_ADDR15=0,LOW_ADDR14=0,LOW_ADDR13=0,LOW_ADDR12=0,LOW_ADDR11=0 */
  setReg8(MPUDESC1, 0x00U);             
  /* MPUDESC0: MSTR0=0,MSTR1=0,MSTR2=0,MSTR3=0,LOW_ADDR22=0,LOW_ADDR21=0,LOW_ADDR20=0,LOW_ADDR19=0 */
  setReg8(MPUDESC0, 0x00U);             
  /* MPUDESC5: HIGH_ADDR10=1,HIGH_ADDR9=1,HIGH_ADDR8=1,HIGH_ADDR7=1,HIGH_ADDR6=1,HIGH_ADDR5=1,HIGH_ADDR4=1,HIGH_ADDR3=1 */
  setReg8(MPUDESC5, 0xFFU);             
  /* MPUDESC4: HIGH_ADDR18=1,HIGH_ADDR17=1,HIGH_ADDR16=1,HIGH_ADDR15=1,HIGH_ADDR14=1,HIGH_ADDR13=1,HIGH_ADDR12=1,HIGH_ADDR11=1 */
  setReg8(MPUDESC4, 0xFFU);             
  /* MPUDESC3: WP=0,NEX=0,??=0,??=0,HIGH_ADDR22=1,HIGH_ADDR21=1,HIGH_ADDR20=1,HIGH_ADDR19=1 */
  setReg8(MPUDESC3, 0x0FU);             
  /* MPUSEL: SVSEN=0,??=0,??=0,??=0,??=0,SEL=0 */
  setReg8(MPUSEL, 0x00U);              /* Select Descriptor num. 0 */ 
  /* MPUDESC2: LOW_ADDR10=0,LOW_ADDR9=0,LOW_ADDR8=0,LOW_ADDR7=0,LOW_ADDR6=0,LOW_ADDR5=0,LOW_ADDR4=0,LOW_ADDR3=0 */
  setReg8(MPUDESC2, 0x00U);             
  /* MPUDESC1: LOW_ADDR18=0,LOW_ADDR17=0,LOW_ADDR16=0,LOW_ADDR15=0,LOW_ADDR14=0,LOW_ADDR13=0,LOW_ADDR12=0,LOW_ADDR11=0 */
  setReg8(MPUDESC1, 0x00U);             
  /* MPUDESC0: MSTR0=1,MSTR1=1,MSTR2=1,MSTR3=0,LOW_ADDR22=0,LOW_ADDR21=0,LOW_ADDR20=0,LOW_ADDR19=0 */
  setReg8(MPUDESC0, 0xE0U);             
  /* MPUDESC5: HIGH_ADDR10=1,HIGH_ADDR9=1,HIGH_ADDR8=1,HIGH_ADDR7=1,HIGH_ADDR6=1,HIGH_ADDR5=1,HIGH_ADDR4=1,HIGH_ADDR3=1 */
  setReg8(MPUDESC5, 0xFFU);             
  /* MPUDESC4: HIGH_ADDR18=1,HIGH_ADDR17=1,HIGH_ADDR16=1,HIGH_ADDR15=1,HIGH_ADDR14=1,HIGH_ADDR13=1,HIGH_ADDR12=1,HIGH_ADDR11=1 */
  setReg8(MPUDESC4, 0xFFU);             
  /* MPUDESC3: WP=0,NEX=0,??=0,??=0,HIGH_ADDR22=1,HIGH_ADDR21=1,HIGH_ADDR20=1,HIGH_ADDR19=1 */
  setReg8(MPUDESC3, 0x0FU);             
  /* Common initialization of the CPU registers */
  /* PERT: PERT7=0,PERT6=0,PERT5=0,PERT4=0,PERT3=0,PERT2=0,PERT1=0,PERT0=0 */
  setReg8(PERT, 0x00U);                 
  /* RDRT: RDRT7=0,RDRT6=0,RDRT5=0,RDRT4=0,RDRT3=0,RDRT2=0,RDRT1=0,RDRT0=0 */
  setReg8(RDRT, 0x00U);                 
  /* MODRR: MODRR6=1,MODRR1=0,MODRR0=0 */
  clrSetReg8Bits(MODRR, 0x03U, 0x40U);  
  /* DDRH: DDRH6=1,DDRH5=1,DDRH4=0 */
  clrSetReg8Bits(DDRH, 0x10U, 0x60U);   
  /* PTH: PTH6=0 */
  clrReg8Bits(PTH, 0x40U);              
  /* PLLCTL: PCE=0 */
  clrReg8Bits(PLLCTL, 0x02U);           
  /* COPCTL: WCOP=0,RSBCK=1,CR2=1,CR1=1,CR0=1 */
  clrSetReg8Bits(COPCTL, 0x80U, 0x47U); 
  /* PERM: PERM7=0,PERM5=0,PERM4=1,PERM3=0,PERM2=0,PERM1=0,PERM0=0 */
  clrSetReg8Bits(PERM, 0xAFU, 0x10U);   
  /* WOMM: WOMM7=0,WOMM5=0,WOMM3=0,WOMM1=0 */
  clrReg8Bits(WOMM, 0xAAU);             
  /* RDRM: RDRM7=0,RDRM6=0,RDRM5=0,RDRM4=0,RDRM3=0,RDRM2=0,RDRM1=0,RDRM0=0 */
  setReg8(RDRM, 0x00U);                 
  /* PWME: PWME7=0,PWME6=0,PWME5=0,PWME4=0,PWME3=0,PWME2=0,PWME1=0,PWME0=0 */
  setReg8(PWME, 0x00U);                 
  /* PWMCTL: CON67=0,CON45=0,CON23=0,CON01=0,PSWAI=0,PFRZ=0 */
  clrReg8Bits(PWMCTL, 0xFCU);           
  /* PWMCAE: CAE7=0,CAE6=0,CAE5=0,CAE4=0,CAE3=0,CAE2=0,CAE1=0,CAE0=0 */
  setReg8(PWMCAE, 0x00U);               
  /* PWMPOL: PPOL7=0,PPOL6=0,PPOL5=0,PPOL4=0,PPOL3=0,PPOL2=0,PPOL1=0,PPOL0=0 */
  setReg8(PWMPOL, 0x00U);               
  /* PTP: PTP7=0,PTP6=0,PTP5=0,PTP4=0,PTP3=0,PTP2=0,PTP1=0,PTP0=0 */
  setReg8(PTP, 0x00U);                  
  /* DDRP: DDRP7=1,DDRP6=1,DDRP5=1,DDRP4=1,DDRP3=1,DDRP2=1,DDRP1=1,DDRP0=1 */
  setReg8(DDRP, 0xFFU);                 
  /* PPSM: PPSM4=0 */
  clrReg8Bits(PPSM, 0x10U);             
  /* CRGINT: LOCKIE=0,SCMIE=0 */
  clrReg8Bits(CRGINT, 0x12U);           
  /* VREGCTRL: LVIE=0 */
  clrReg8Bits(VREGCTRL, 0x02U);         
  /* DDR0AD1: DDR0AD17=1,DDR0AD16=1,DDR0AD15=1,DDR0AD14=1,DDR0AD13=1,DDR0AD12=1,DDR0AD11=1,DDR0AD10=1 */
  setReg8(DDR0AD1, 0xFFU);              
  /* DDRF: DDRF7=1,DDRF6=1,DDRF5=1,DDRF4=1,DDRF3=1,DDRF2=1,DDRF1=1,DDRF0=1 */
  setReg8(DDRF, 0xFFU);                 
  /* DDRJ: DDRJ3=1 */
  setReg8Bits(DDRJ, 0x08U);             
  /* DDRL: DDRL7=1,DDRL6=1,DDRL5=1,DDRL4=1,DDRL3=1,DDRL2=1,DDRL1=1,DDRL0=1 */
  setReg8(DDRL, 0xFFU);                 
  /* DDRR: DDRR7=1,DDRR6=1,DDRR5=1,DDRR4=1,DDRR3=1,DDRR2=1,DDRR1=1,DDRR0=1 */
  setReg8(DDRR, 0xFFU);                 
  /* RDRIV: RDPK=0,RDPE=0,RDPD=0,RDPC=0,RDPB=0,RDPA=0 */
  clrReg8Bits(RDRIV, 0x9FU);            
  /* RDR1AD1: RDR1AD17=0,RDR1AD16=0,RDR1AD15=0,RDR1AD14=0,RDR1AD13=0,RDR1AD12=0,RDR1AD11=0,RDR1AD10=0 */
  setReg8(RDR1AD1, 0x00U);              
  /* RDRH: RDRH7=0,RDRH6=0,RDRH5=0,RDRH4=0,RDRH3=0,RDRH2=0,RDRH1=0,RDRH0=0 */
  setReg8(RDRH, 0x00U);                 
  /* RDRJ: RDRJ7=0,RDRJ6=0,RDRJ5=0,RDRJ4=0,RDRJ2=0,RDRJ1=0,RDRJ0=0 */
  clrReg8Bits(RDRJ, 0xF7U);             
  /* RDRP: RDRP7=0,RDRP6=0,RDRP5=0,RDRP4=0,RDRP3=0,RDRP2=0,RDRP1=0,RDRP0=0 */
  setReg8(RDRP, 0x00U);                 
  /* RDRS: RDRS7=0,RDRS6=0,RDRS5=0,RDRS4=0,RDRS3=0,RDRS2=0,RDRS1=0,RDRS0=0 */
  setReg8(RDRS, 0x00U);                 
  /* RDR0AD0: RDR0AD07=0,RDR0AD06=0,RDR0AD05=0,RDR0AD04=0,RDR0AD03=0,RDR0AD02=0,RDR0AD01=0,RDR0AD00=0 */
  setReg8(RDR0AD0, 0x00U);              
  /* RDR1AD0: RDR1AD07=0,RDR1AD06=0,RDR1AD05=0,RDR1AD04=0,RDR1AD03=0,RDR1AD02=0,RDR1AD01=0,RDR1AD00=0 */
  setReg8(RDR1AD0, 0x00U);              
  /* IRQCR: IRQEN=0 */
  clrReg8Bits(IRQCR, 0x40U);            
  /* ATD0DIEN: IEN15=0,IEN14=0,IEN13=0,IEN12=0,IEN11=0,IEN10=0,IEN9=0,IEN8=0,IEN7=0,IEN6=0,IEN5=0,IEN4=0,IEN3=0,IEN2=0,IEN1=0,IEN0=0 */
  setReg16(ATD0DIEN, 0x00U);            
  /* ATD1DIEN: IEN6=0,IEN5=0,IEN4=0,IEN3=0,IEN2=0,IEN1=0,IEN0=0 */
  clrReg16Bits(ATD1DIEN, 0x7FU);        
  /* ### MC9S12XEP100_144 "Cpu" init code ... */
  /* ###  "AD0" init code ... */
  AD0_Init();
  /* ###  "AD1" init code ... */
  AD1_Init();
  /* ### Init_GPIO "GPIOA" init code ... */
  GPIOA_Init();
  /* ### Init_GPIO "GPIOB" init code ... */
  GPIOB_Init();
  /* ### Init_GPIO "GPIOC" init code ... */
  GPIOC_Init();
  /* ### Init_GPIO "GPIOD" init code ... */
  GPIOD_Init();
  /* ### Init_GPIO "GPIOE" init code ... */
  GPIOE_Init();
  /* ### Init_GPIO "GPIOH" init code ... */
  GPIOH_Init();
  /* ### Init_GPIO "GPIOJ" init code ... */
  GPIOJ_Init();
  /* ### Init_GPIO "GPIOK" init code ... */
  GPIOK_Init();
  /* ### Init_GPIO "GPIOS" init code ... */
  GPIOS_Init();
  /* ### Init_ECT "ECT" init code ... */
   ECT_Init();
  /* ###  Synchro master "SPI2" init code ... */
  SPI2_Init();
  /* ###  WatchDog "Wdg" init code ... */
  /* ### Init_MSCAN "CAN0" init code ... */
  CAN0_Init();
  /* ### Init_MSCAN "CAN1" init code ... */
  CAN1_Init();
  /* ### Init_API "TickTimer" init code ... */
  /* ### Call "TickTimer_Init();" init method in a user code, i.e. in the main code */
  /* ### Note:   To enable automatic calling of the "TickTimer" init code here must be
                 set the property Call Init method to 'yes'
  */
  /* ### Init_PIT "TimeStamp" init code ... */
  TimeStamp_Init();
  /* ### Programable pulse generation "PWM0" init code ... */
  PWM0_Init();
  /* ### Programable pulse generation "PWM1" init code ... */
  PWM1_Init();
  /* ### Programable pulse generation "PWM2" init code ... */
  PWM2_Init();
  /* ### Programable pulse generation "PWM3" init code ... */
  PWM3_Init();
  /* ### Programable pulse generation "PWM4" init code ... */
  PWM4_Init();
  /* ### Programable pulse generation "PWM5" init code ... */
  PWM5_Init();
  /* ### Programable pulse generation "PWM6" init code ... */
  PWM6_Init();
  /* ### Programable pulse generation "PWM7" init code ... */
  PWM7_Init();
  /* ###  IntFLASH "Flash" init code ... */
  Flash_Init();
  /* ### IntEEPROM "EEPROM" init code ... */
  EEPROM_Init();
  /* ### Init_MSCAN "CAN2" init code ... */
  CAN2_Init();
  /* ### Init_MSCAN "CAN3" init code ... */
  CAN3_Init();
  __DI();                              /* Disable interrupts */
}

/*lint -save  -e950 Disable MISRA rule (1.1) checking. */
/* Initialization of the CPU registers in FLASH */
/*lint -restore Enable MISRA rule (1.1) checking. */

#pragma CODE_SEG __NEAR_SEG NON_BANKED

/*
** ===================================================================
**     Method      :  _EntryPoint (component MC9S12XEP100_144)
**
**     Description :
**         Initializes the whole system like timing and so on. At the end 
**         of this function, the C startup is invoked to initialize stack,
**         memory areas and so on.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
extern void _Startup(void);            /* Forward declaration of external startup function declared in file Start12.c */
#pragma OPTION ADD "-Onf"              /* 'Create Sub-Functions with Common Code optimalization' must be disabled because stack is not yet initialized */

#pragma NO_FRAME                       /* Suppress generation of frame code */
#pragma NO_EXIT                        /* Suppress generation of exit from a function */
void _EntryPoint(void)
{
  /* ### MC9S12XEP100_144 "Cpu" init code ... */
  /*  PE initialization code after reset */
  /* MMCCTL1: TGMRAMON=0,??=0,EEEIFRON=0,PGMIFRON=0,RAMHM=0,EROMON=0,ROMHM=0,ROMON=1 */
  setReg8(MMCCTL1, 0x01U);              
  /* DIRECT: DP15=0,DP14=0,DP13=0,DP12=0,DP11=0,DP10=0,DP9=0,DP8=0 */
  setReg8(DIRECT, 0x00U);               
  /* IVBR: IVB_ADDR=0xFF */
  setReg8(IVBR, 0xFFU);                 
  /* ECLKCTL: NECLK=1,NCLKX2=1,DIV16=0,EDIV4=0,EDIV3=0,EDIV2=0,EDIV1=0,EDIV0=0 */
  setReg8(ECLKCTL, 0xC0U);              
  /*  System clock initialization */
  /* CLKSEL: PLLSEL=0,PSTP=0,XCLKS=0,??=0,PLLWAI=0,??=0,RTIWAI=0,COPWAI=0 */
  setReg8(CLKSEL, 0x00U);              /* Select clock source from XTAL and set bits in CLKSEL reg. */ 
  /* PLLCTL: CME=1,PLLON=0,FM1=0,FM0=0,FSTWKP=0,PRE=0,PCE=0,SCME=1 */
  setReg8(PLLCTL, 0x81U);              /* Disable the PLL */ 
  /* SYNR: VCOFRQ1=0,VCOFRQ0=1,SYNDIV5=0,SYNDIV4=0,SYNDIV3=0,SYNDIV2=1,SYNDIV1=0,SYNDIV0=0 */
  setReg8(SYNR, 0x44U);                /* Set the multiplier register */ 
  /* REFDV: REFFRQ1=1,REFFRQ0=0,REFDIV5=0,REFDIV4=0,REFDIV3=0,REFDIV2=0,REFDIV1=0,REFDIV0=1 */
  setReg8(REFDV, 0x81U);               /* Set the divider register */ 
  /* POSTDIV: ??=0,??=0,??=0,POSTDIV4=0,POSTDIV3=0,POSTDIV2=0,POSTDIV1=0,POSTDIV0=0 */
  setReg8(POSTDIV, 0x00U);             /* Set the post divider register */ 
  /* PLLCTL: CME=1,PLLON=1,FM1=0,FM0=0,FSTWKP=0,PRE=0,PCE=0,SCME=1 */
  setReg8(PLLCTL, 0xC1U);               
  while(CRGFLG_LOCK == 0U) {           /* Wait until the PLL is within the desired tolerance of the target frequency */
  }
  /* CLKSEL: PLLSEL=1 */
  setReg8Bits(CLKSEL, 0x80U);          /* Select clock source from PLL */ 
  /* VREGHTCL: ??=0,??=0,VSEL=0,VAE=1,HTEN=0,HTDS=0,HTIE=0,HTIF=0 */
  setReg8(VREGHTCL, 0x10U);             
  /*** End of PE initialization code after reset ***/
  /*lint -save  -e950 Disable MISRA rule (1.1) checking. */
  __asm("jmp _Startup");               /* Jump to C startup code */
  /*lint -restore Enable MISRA rule (1.1) checking. */
}

#pragma CODE_SEG DEFAULT
/* END Cpu. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
