/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : ECT.c
**     Project   : Project
**     Processor : MC9S12XEP100MAG
**     Component : Init_ECT
**     Version   : Component 01.220, Driver 01.09, CPU db: 3.00.036
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2016/8/14, 15:02
**     Abstract  :
**          This file implements the ECT (ECT_Counter) module initialization
**          according to the Peripheral Initialization Bean settings,
**          and defines interrupt service routines prototypes.
**          The HCS12 Enhanced Capture Timer module has the features of the
**          HCS12 Standard Timer module enhanced by additional features
**          in order to enlarge the field of applications, in particular
**          for automotive ABS applications.
**          Features
**          • 16-Bit Buffer Register for four Input Capture (IC) channels.
**          • Four 8-Bit Pulse Accumulators with 8-bit buffer registers
**          associated with the four buffered IC channels. Configurable
**          also as two 16-Bit Pulse Accumulators.
**          • 16-Bit Modulus Down-Counter with 4-bit Prescaler.
**          • Four user selectable Delay Counters for input noise immunity increase.
**     Settings  :
**          Component name                                 : ECT
**          Device                                         : ECT
**          Settings                                       : 
**            Clock settings                               : 
**              Prescaler                                  : Bus Clock / 128
**              Timer Clock Source                         : Timer prescaler
**              Frequency                                  : 312.5 kHz
**              Precision timer                            : Disabled
**            Fast Flag Clear                              : yes
**            Timer Counter Reset                          : Disabled
**            Stop in wait mode                            : no
**            Stop in freeze mode                          : no
**            Delay Counter                                : Disabled
**            Mode                                         : Queue
**            Buffer                                       : yes
**            Timer flag mode                              : New value in Capture
**            8-bit Pulse accumulator max. count           : no
**            Share input action                           : 
**              Share capture channels 3 & 7               : no
**              Share capture channels 2 & 6               : no
**              Share capture channels 1 & 5               : no
**              Share capture channels 0 & 4               : no
**            Accumulator A                                : 
**              Accumulator counter                        : ECTPACNT23
**              Pulse Accumulator Mode                     : Event counter
**                Edge Control                             : Falling
**              Count register 2                           : 0
**              Count register 3                           : 0
**            Accumulator B                                : 
**              Accumulator counter                        : ECTPACNT01
**              Count register 0                           : 0
**              Count register 1                           : 0
**            Modulus Counter                              : 
**              Modulus counter                            : ModulusCounter
**              Modulus mode                               : no
**              Read                                       : Value of the count register
**              Count register                             : 65535
**              Clock settings                             : 
**                Prescaler                                : 1
**                Frequency                                : 40000 kHz
**          Channels                                       : 
**            Channel 0                                    : 
**              Channel device                             : ECTTC0
**              Mode                                       : Capture
**              Compare Mask                               : Disabled
**              Compare Data                               : 0
**              Toggle On Overflow                         : no
**              Output action                              : Disconected
**              Output Compare Pin                         : Enabled
**              Input control                              : Capture on any edge
**              Capture/Compare register                   : 0
**              Capture register Overwrite                 : no
**              Channel 0 interrupt                        : 
**                Channel interrupt                        : Enabled
**                Interrupt                                : Vectch0
**                Priority                                 : 4
**                ISR name                                 : CapPT0
**              Pin                                        : Enabled
**                Pin                                      : PT0_IOC0
**                Pin signal                               : 
**                Pin pull resistor                        : no pull
**                Pin open drain                           : push-pull
**            Channel 1                                    : 
**              Channel device                             : ECTTC1
**              Mode                                       : Capture
**              Compare Mask                               : Disabled
**              Compare Data                               : 0
**              Toggle On Overflow                         : no
**              Output action                              : Disconected
**              Output Compare Pin                         : Enabled
**              Input control                              : Capture on any edge
**              Capture/Compare register                   : 0
**              Capture register Overwrite                 : no
**              Channel 1 interrupt                        : 
**                Channel interrupt                        : Enabled
**                Interrupt                                : Vectch1
**                Priority                                 : 4
**                ISR name                                 : CapPT1
**              Pin                                        : Enabled
**                Pin                                      : PT1_IOC1
**                Pin signal                               : 
**                Pin pull resistor                        : no pull
**                Pin open drain                           : push-pull
**            Channel 2                                    : 
**              Channel device                             : ECTTC2
**              Mode                                       : Capture
**              Compare Mask                               : Disabled
**              Compare Data                               : 0
**              Toggle On Overflow                         : no
**              Output action                              : Disconected
**              Output Compare Pin                         : Enabled
**              Input control                              : Capture on any edge
**              Capture/Compare register                   : 0
**              Capture register Overwrite                 : no
**              Channel 2 interrupt                        : 
**                Channel interrupt                        : Enabled
**                Interrupt                                : Vectch2
**                Priority                                 : 4
**                ISR name                                 : CapPT2
**              Pin                                        : Enabled
**                Pin                                      : PT2_IOC2
**                Pin signal                               : 
**                Pin pull resistor                        : no pull
**                Pin open drain                           : push-pull
**            Channel 3                                    : 
**              Channel device                             : ECTTC3
**              Mode                                       : Capture
**              Compare Mask                               : Disabled
**              Compare Data                               : 0
**              Toggle On Overflow                         : no
**              Output action                              : Disconected
**              Output Compare Pin                         : Enabled
**              Input control                              : Capture on any edge
**              Capture/Compare register                   : 0
**              Capture register Overwrite                 : no
**              Channel 3 interrupt                        : 
**                Channel interrupt                        : Enabled
**                Interrupt                                : Vectch3
**                Priority                                 : 4
**                ISR name                                 : CapPT3
**              Pin                                        : Enabled
**                Pin                                      : PT3_IOC3
**                Pin signal                               : 
**                Pin pull resistor                        : no pull
**                Pin open drain                           : push-pull
**            Channel 4                                    : 
**              Channel device                             : ECTTC4
**              Mode                                       : Capture
**              Compare Mask                               : Disabled
**              Compare Data                               : 0
**              Toggle On Overflow                         : no
**              Output action                              : Disconected
**              Output Compare Pin                         : Enabled
**              Input control                              : Capture on any edge
**              Capture/Compare register                   : 0
**              Capture register Overwrite                 : no
**              Channel 4 interrupt                        : 
**                Channel interrupt                        : Enabled
**                Interrupt                                : Vectch4
**                Priority                                 : 4
**                ISR name                                 : CapPT4
**              Pin                                        : Enabled
**                Pin                                      : PT4_IOC4
**                Pin signal                               : 
**                Pin pull resistor                        : no pull
**                Pin open drain                           : push-pull
**            Channel 5                                    : 
**              Channel device                             : ECTTC5
**              Mode                                       : Capture
**              Compare Mask                               : Disabled
**              Compare Data                               : 0
**              Toggle On Overflow                         : no
**              Output action                              : Disconected
**              Output Compare Pin                         : Enabled
**              Input control                              : Capture on any edge
**              Capture/Compare register                   : 0
**              Capture register Overwrite                 : no
**              Channel 5 interrupt                        : 
**                Channel interrupt                        : Enabled
**                Interrupt                                : Vectch5
**                Priority                                 : 4
**                ISR name                                 : CapPT5
**              Pin                                        : Enabled
**                Pin                                      : PT5_IOC5_VREGAPI
**                Pin signal                               : 
**                Pin pull resistor                        : no pull
**                Pin open drain                           : push-pull
**            Channel 6                                    : 
**              Channel device                             : ECTTC6
**              Mode                                       : Capture
**              Compare Mask                               : Disabled
**              Compare Data                               : 0
**              Toggle On Overflow                         : no
**              Output action                              : Disconected
**              Output Compare Pin                         : Enabled
**              Input control                              : Capture on any edge
**              Capture/Compare register                   : 0
**              Capture register Overwrite                 : no
**              Channel 6 interrupt                        : 
**                Channel interrupt                        : Enabled
**                Interrupt                                : Vectch6
**                Priority                                 : 4
**                ISR name                                 : CapPT6
**              Pin                                        : Enabled
**                Pin                                      : PT6_IOC6
**                Pin signal                               : 
**                Pin pull resistor                        : no pull
**                Pin open drain                           : push-pull
**            Channel 7                                    : 
**              Channel device                             : ECTTC7
**              Mode                                       : Capture
**              Compare Mask                               : Disabled
**              Compare Data                               : 0
**              Toggle On Overflow                         : no
**              Output action                              : Disconected
**              Output Compare Pin                         : Enabled
**              Input control                              : Capture on any edge
**              Capture/Compare register                   : 0
**              Capture register Overwrite                 : no
**              Channel 7 interrupt                        : 
**                Channel interrupt                        : Enabled
**                Interrupt                                : Vectch7
**                Priority                                 : 4
**                ISR name                                 : CapPT7
**              Pin                                        : Enabled
**                Pin                                      : PT7_IOC7
**                Pin signal                               : 
**                Pin pull resistor                        : no pull
**                Pin open drain                           : push-pull
**          Interrupts                                     : 
**            Timer Overflow                               : 
**              Timer Overflow                             : Disabled
**              Interrupt                                  : Vectovf
**              Priority                                   : 4
**              ISR name                                   : ECT_OVF
**            Accumulator A Overflow                       : 
**              Accumulator A Overflow                     : Disabled
**              Interrupt                                  : Vectpaaovf
**              Priority                                   : 1
**              ISR name                                   : 
**            Accumulator A Input                          : 
**              Accumulator A Input                        : Disabled
**              Interrupt                                  : Vectpaie
**              Priority                                   : 1
**              ISR name                                   : 
**            Accumulator B Overflow                       : 
**              Accumulator B Overflow                     : Disabled
**              Interrupt                                  : Vectpabovf
**              Priority                                   : 1
**              ISR name                                   : 
**            Modulus counter Underflow                    : 
**              Modulus counter Underflow                  : Disabled
**              Interrupt                                  : Vectmdcu
**              Priority                                   : 1
**              ISR name                                   : 
**          Initialization                                 : 
**            Call Init method                             : yes
**            Timer                                        : Enabled
**            Modulus Counter                              : Disabled
**            Pulse Accumulator A                          : Disabled
**            Pulse Accumulator B                          : Disabled
**            Pulse accumulator 0                          : Disabled
**            Pulse accumulator 1                          : Disabled
**            Pulse accumulator 2                          : Disabled
**            Pulse accumulator 3                          : Disabled
**     Contents  :
**         Init - void ECT_Init(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE ECT. */

#include "ECT.h"

/*
** ###################################################################
**
**  The interrupt service routine(s) must be implemented
**  by user in one of the following user modules.
**
**  If the "Generate ISR" option is enabled, Processor Expert generates
**  ISR templates in the CPU event module.
**
**  User modules:
**      Project.c
**      Events.c
**
** ###################################################################
#pragma CODE_SEG __NEAR_SEG NON_BANKED
ISR(CapPT0)
        {
        // NOTE: The routine should include the following actions to obtain
        //          correct functionality of the hardware.
        //
        //      This ISR is invoked by Input Capture/Output Compare Channel 0 flag (C0F).
        //      To clear the flag, write a one to the bit C0F in TFLG1 register.
        //      When TFFCA bit in TSCR register is set, a read from an input
        //      capture or a write into an output compare channel will cause
        //      the corresponding channel flag CxF to be cleared.
        //      Example: TFLG1 = TFLG1_C0F_MASK;
        }
ISR(CapPT1)
        {
        // NOTE: The routine should include the following actions to obtain
        //          correct functionality of the hardware.
        //
        //      This ISR is invoked by Input Capture/Output Compare Channel 1 flag (C1F).
        //      To clear the flag, write a one to the bit C1F in TFLG1 register.
        //      When TFFCA bit in TSCR register is set, a read from an input
        //      capture or a write into an output compare channel will cause
        //      the corresponding channel flag CxF to be cleared.
        //      Example: TFLG1 = TFLG1_C1F_MASK;
        }
ISR(CapPT2)
        {
        // NOTE: The routine should include the following actions to obtain
        //          correct functionality of the hardware.
        //
        //      This ISR is invoked by Input Capture/Output Compare Channel 2 flag (C2F).
        //      To clear the flag, write a one to the bit C2F in TFLG1 register.
        //      When TFFCA bit in TSCR register is set, a read from an input
        //      capture or a write into an output compare channel will cause
        //      the corresponding channel flag CxF to be cleared.
        //      Example: TFLG1 = TFLG1_C2F_MASK;
        }
ISR(CapPT3)
        {
        // NOTE: The routine should include the following actions to obtain
        //          correct functionality of the hardware.
        //
        //      This ISR is invoked by Input Capture/Output Compare Channel 3 flag (C3F).
        //      To clear the flag, write a one to the bit C3F in TFLG1 register.
        //      When TFFCA bit in TSCR register is set, a read from an input
        //      capture or a write into an output compare channel will cause
        //      the corresponding channel flag CxF to be cleared.
        //      Example: TFLG1 = TFLG1_C3F_MASK;
        }
ISR(CapPT4)
        {
        // NOTE: The routine should include the following actions to obtain
        //          correct functionality of the hardware.
        //
        //      This ISR is invoked by Input Capture/Output Compare Channel 4 flag (C4F).
        //      To clear the flag, write a one to the bit C4F in TFLG1 register.
        //      When TFFCA bit in TSCR register is set, a read from an input
        //      capture or a write into an output compare channel will cause
        //      the corresponding channel flag CxF to be cleared.
        //      Example: TFLG1 = TFLG1_C4F_MASK;
        }
ISR(CapPT5)
        {
        // NOTE: The routine should include the following actions to obtain
        //          correct functionality of the hardware.
        //
        //      This ISR is invoked by Input Capture/Output Compare Channel 5 flag (C5F).
        //      To clear the flag, write a one to the bit C5F in TFLG1 register.
        //      When TFFCA bit in TSCR register is set, a read from an input
        //      capture or a write into an output compare channel will cause
        //      the corresponding channel flag CxF to be cleared.
        //      Example: TFLG1 = TFLG1_C5F_MASK;
        }
ISR(CapPT6)
        {
        // NOTE: The routine should include the following actions to obtain
        //          correct functionality of the hardware.
        //
        //      This ISR is invoked by Input Capture/Output Compare Channel 6 flag (C6F).
        //      To clear the flag, write a one to the bit C6F in TFLG1 register.
        //      When TFFCA bit in TSCR register is set, a read from an input
        //      capture or a write into an output compare channel will cause
        //      the corresponding channel flag CxF to be cleared.
        //      Example: TFLG1 = TFLG1_C6F_MASK;
        }
ISR(CapPT7)
        {
        // NOTE: The routine should include the following actions to obtain
        //          correct functionality of the hardware.
        //
        //      This ISR is invoked by Input Capture/Output Compare Channel 7 flag (C7F).
        //      To clear the flag, write a one to the bit C7F in TFLG1 register.
        //      When TFFCA bit in TSCR register is set, a read from an input
        //      capture or a write into an output compare channel will cause
        //      the corresponding channel flag CxF to be cleared.
        //      Example: TFLG1 = TFLG1_C7F_MASK;
        }
ISR(ECT_OVF)
        {
        // NOTE: The routine should include the following actions to obtain
        //       correct functionality of the hardware.
        //
        //      This ISR is invoked by TOF flag. To clear the flag, write a one
        //      to the bit T0F in TFLG2 register. Any access to TCNT will
        //      clear TFLG2 register if the TFFCA bit in TSCR register is set.
        //      Example: TFLG2_T0F=1;
        }
#pragma CODE_SEG DEFAULT
*/
/*
** ===================================================================
**     Method      :  ECT_Init (component Init_ECT)
**
**     Description :
**         This method initializes registers of the ECT module
**         according to this Peripheral Initialization Bean settings.
**         Call this method in user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the bean for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void ECT_Init(void)
{
  /* ECT_TSCR1: TEN=0 */
  clrReg8Bits(ECT_TSCR1, 0x80U);        
  /* ECT_TIE: C7I=0,C6I=0,C5I=0,C4I=0,C3I=0,C2I=0,C1I=0,C0I=0 */
  setReg8(ECT_TIE, 0x00U);              
  /* ECT_PACTL: PAEN=0,PAI=0 */
  clrReg8Bits(ECT_PACTL, 0x41U);        
  /* ECT_ICPAR: ??=0,??=0,??=0,??=0,PA3EN=0,PA2EN=0,PA1EN=0,PA0EN=0 */
  setReg8(ECT_ICPAR, 0x00U);            
  /* ECT_ICOVW: NOVW7=0,NOVW6=0,NOVW5=0,NOVW4=0,NOVW3=0,NOVW2=0,NOVW1=0,NOVW0=0 */
  setReg8(ECT_ICOVW, 0x00U);            
  /* ECT_TCTL4: EDG3B=1,EDG3A=1,EDG2B=1,EDG2A=1,EDG1B=1,EDG1A=1,EDG0B=1,EDG0A=1 */
  setReg8(ECT_TCTL4, 0xFFU);            
  /* ECT_TCTL3: EDG7B=1,EDG7A=1,EDG6B=1,EDG6A=1,EDG5B=1,EDG5A=1,EDG4B=1,EDG4A=1 */
  setReg8(ECT_TCTL3, 0xFFU);            
  /* ECT_TCTL2: OM3=0,OL3=0,OM2=0,OL2=0,OM1=0,OL1=0,OM0=0,OL0=0 */
  setReg8(ECT_TCTL2, 0x00U);            
  /* ECT_TCTL1: OM7=0,OL7=0,OM6=0,OL6=0,OM5=0,OL5=0,OM4=0,OL4=0 */
  setReg8(ECT_TCTL1, 0x00U);            
  /* ECT_PACN0: BIT7=0,BIT6=0,BIT5=0,BIT4=0,BIT3=0,BIT2=0,BIT1=0,BIT0=0 */
  setReg8(ECT_PACN0, 0x00U);            
  /* ECT_OCPD: OCPD7=0,OCPD6=0,OCPD5=0,OCPD4=0,OCPD3=0,OCPD2=0,OCPD1=0,OCPD0=0 */
  setReg8(ECT_OCPD, 0x00U);             
  /* ECT_PACN1: BIT7=0,BIT6=0,BIT5=0,BIT4=0,BIT3=0,BIT2=0,BIT1=0,BIT0=0 */
  setReg8(ECT_PACN1, 0x00U);            
  /* ECT_PACN2: BIT7=0,BIT6=0,BIT5=0,BIT4=0,BIT3=0,BIT2=0,BIT1=0,BIT0=0 */
  setReg8(ECT_PACN2, 0x00U);            
  /* ECT_PACN3: BIT7=0,BIT6=0,BIT5=0,BIT4=0,BIT3=0,BIT2=0,BIT1=0,BIT0=0 */
  setReg8(ECT_PACN3, 0x00U);            
  /* ECT_TIOS: IOS7=0,IOS6=0,IOS5=0,IOS4=0,IOS3=0,IOS2=0,IOS1=0,IOS0=0 */
  setReg8(ECT_TIOS, 0x00U);             
  /* ECT_TC0: BIT15=0,BIT14=0,BIT13=0,BIT12=0,BIT11=0,BIT10=0,BIT9=0,BIT8=0,BIT7=0,BIT6=0,BIT5=0,BIT4=0,BIT3=0,BIT2=0,BIT1=0,BIT0=0 */
  setReg16(ECT_TC0, 0x00U);             
  /* ECT_TC1: BIT15=0,BIT14=0,BIT13=0,BIT12=0,BIT11=0,BIT10=0,BIT9=0,BIT8=0,BIT7=0,BIT6=0,BIT5=0,BIT4=0,BIT3=0,BIT2=0,BIT1=0,BIT0=0 */
  setReg16(ECT_TC1, 0x00U);             
  /* ECT_TC2: BIT15=0,BIT14=0,BIT13=0,BIT12=0,BIT11=0,BIT10=0,BIT9=0,BIT8=0,BIT7=0,BIT6=0,BIT5=0,BIT4=0,BIT3=0,BIT2=0,BIT1=0,BIT0=0 */
  setReg16(ECT_TC2, 0x00U);             
  /* ECT_TC3: BIT15=0,BIT14=0,BIT13=0,BIT12=0,BIT11=0,BIT10=0,BIT9=0,BIT8=0,BIT7=0,BIT6=0,BIT5=0,BIT4=0,BIT3=0,BIT2=0,BIT1=0,BIT0=0 */
  setReg16(ECT_TC3, 0x00U);             
  /* ECT_TC4: BIT15=0,BIT14=0,BIT13=0,BIT12=0,BIT11=0,BIT10=0,BIT9=0,BIT8=0,BIT7=0,BIT6=0,BIT5=0,BIT4=0,BIT3=0,BIT2=0,BIT1=0,BIT0=0 */
  setReg16(ECT_TC4, 0x00U);             
  /* ECT_TC5: BIT15=0,BIT14=0,BIT13=0,BIT12=0,BIT11=0,BIT10=0,BIT9=0,BIT8=0,BIT7=0,BIT6=0,BIT5=0,BIT4=0,BIT3=0,BIT2=0,BIT1=0,BIT0=0 */
  setReg16(ECT_TC5, 0x00U);             
  /* ECT_TC6: BIT15=0,BIT14=0,BIT13=0,BIT12=0,BIT11=0,BIT10=0,BIT9=0,BIT8=0,BIT7=0,BIT6=0,BIT5=0,BIT4=0,BIT3=0,BIT2=0,BIT1=0,BIT0=0 */
  setReg16(ECT_TC6, 0x00U);             
  /* ECT_TC7: BIT15=0,BIT14=0,BIT13=0,BIT12=0,BIT11=0,BIT10=0,BIT9=0,BIT8=0,BIT7=0,BIT6=0,BIT5=0,BIT4=0,BIT3=0,BIT2=0,BIT1=0,BIT0=0 */
  setReg16(ECT_TC7, 0x00U);             
  /* ECT_TFLG2: TOF=1,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg8(ECT_TFLG2, 0x80U);            
  /* ECT_TSCR2: TOI=0,??=0,??=0,??=0,TCRE=0,PR2=1,PR1=1,PR0=1 */
  setReg8(ECT_TSCR2, 0x07U);            
  /* ECT_TFLG1: C7F=1,C6F=1,C5F=1,C4F=1,C3F=1,C2F=1,C1F=1,C0F=1 */
  setReg8(ECT_TFLG1, 0xFFU);            
  /* ECT_TIE: C7I=1,C6I=1,C5I=1,C4I=1,C3I=1,C2I=1,C1I=1,C0I=1 */
  setReg8(ECT_TIE, 0xFFU);              
  /* ECT_TTOV: TOV7=0,TOV6=0,TOV5=0,TOV4=0,TOV3=0,TOV2=0,TOV1=0,TOV0=0 */
  setReg8(ECT_TTOV, 0x00U);             
  /* ECT_OC7D: OC7D7=0,OC7D6=0,OC7D5=0,OC7D4=0,OC7D3=0,OC7D2=0,OC7D1=0,OC7D0=0 */
  setReg8(ECT_OC7D, 0x00U);             
  /* ECT_OC7M: OC7M7=0,OC7M6=0,OC7M5=0,OC7M4=0,OC7M3=0,OC7M2=0,OC7M1=0,OC7M0=0 */
  setReg8(ECT_OC7M, 0x00U);             
  /* ECT_DLYCT: DLY7=0,DLY6=0,DLY5=0,DLY4=0,DLY3=0,DLY2=0,DLY1=0,DLY0=0 */
  setReg8(ECT_DLYCT, 0x00U);            
  /* ECT_PTPSR: PTPS7=0,PTPS6=0,PTPS5=0,PTPS4=0,PTPS3=0,PTPS2=0,PTPS1=0,PTPS0=0 */
  setReg8(ECT_PTPSR, 0x00U);            
  /* ECT_PTMCPSR: PTMPS7=0,PTMPS6=0,PTMPS5=0,PTMPS4=0,PTMPS3=0,PTMPS2=0,PTMPS1=0,PTMPS0=0 */
  setReg8(ECT_PTMCPSR, 0x00U);          
  /* ECT_ICSYS: SH37=0,SH26=0,SH15=0,SH04=0,TFMOD=0,PACMX=0,BUFEN=1,LATQ=0 */
  setReg8(ECT_ICSYS, 0x02U);            
  /* ECT_TSCR1: TEN=1,TSWAI=0,TSFRZ=0,TFFCA=1,PRNT=0,??=0,??=0,??=0 */
  setReg8(ECT_TSCR1, 0x90U);            
  /* ECT_MCFLG: MCZF=1,??=0,??=0,??=0,POLF3=0,POLF2=0,POLF1=0,POLF0=0 */
  setReg8(ECT_MCFLG, 0x80U);            
  /* ECT_MCCTL: MCZI=0,MODMC=0,RDMCL=0,ICLAT=0,FLMC=0,MCEN=0,MCPR1=0,MCPR0=0 */
  setReg8(ECT_MCCTL, 0x00U);            
  /* ECT_MCCNT: BIT15=1,BIT14=1,BIT13=1,BIT12=1,BIT11=1,BIT10=1,BIT9=1,BIT8=1,BIT7=1,BIT6=1,BIT5=1,BIT4=1,BIT3=1,BIT2=1,BIT1=1,BIT0=1 */
  setReg16(ECT_MCCNT, 0xFFFFU);         
  /* ECT_PAFLG: ??=0,??=0,??=0,??=0,??=0,??=0,PAOVF=1,PAIF=1 */
  setReg8(ECT_PAFLG, 0x03U);            
  /* ECT_PACTL: ??=0,PAEN=0,PAMOD=0,PEDGE=0,CLK1=0,CLK0=0,PAOVI=0,PAI=0 */
  setReg8(ECT_PACTL, 0x00U);            
  /* ECT_PBFLG: ??=0,??=0,??=0,??=0,??=0,??=0,PBOVF=1,??=0 */
  setReg8(ECT_PBFLG, 0x02U);            
  /* ECT_PBCTL: ??=0,PBEN=0,??=0,??=0,??=0,??=0,PBOVI=0,??=0 */
  setReg8(ECT_PBCTL, 0x00U);            
}

/* END ECT. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
