/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : EEPROM.c
**     Project   : Project
**     Processor : MC9S12XEP100MAG
**     Component : IntEEPROM
**     Version   : Component 02.200, Driver 01.25, CPU db: 3.00.036
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2016/8/14, 15:02
**     Abstract  :
**         This device "IntEEPROM" implements internal EEPROM
**     Comment   :
**         The EEPROM array is organized as rows of word (2 bytes), the EEPROM block's
**         erase sector size is 2 rows (2 words). Therefore it is preferable
**         to use word aligned data for writting - methods SetWord and SetLong -
**         with word aligned address.
**         Driver expects that all security options of EEPROM are disabled.
**         If some security option is enabled methods performing write
**         operation (such as SetWord) can return error.
**     Settings  :
**         EEPROM size                 : 32768 byte
**         Initialization:
**              Wait in methods        : Enabled
**              EEPROM clock           : High: 1000 kHz
**
**     Contents  :
**         SetByte - byte EEPROM_SetByte(EEPROM_TAddress Addr, byte Data);
**         GetByte - byte EEPROM_GetByte(EEPROM_TAddress Addr, byte *Data);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/


/* MODULE EEPROM. */

#include "EEPROM.h"

/* Internal type for addressing of the EEPROM. */
typedef const far word * far EEPROM_TAddress_; /* Type of address to the EEPROM */

#pragma DATA_SEG EEPROM_DATA           /* Select data segment "EEPROM_DATA" */
#pragma CODE_SEG EEPROM_CODE

#pragma MESSAGE DISABLE C12056         /* Disable warning C12056 "SP debug info incorrect becouse of optimization or inline assembler" */
/*lint -save  -e923 -e926 -e927 -e928 -e929 Disable MISRA rule (11.3,11.4) checking. */

static word BackupArray[0x80];         /* Array for backup data from erased sector */


/*
** ===================================================================
**     Method      :  BackupSector (component IntEEPROM)
**
**     Description :
**         The method backups the content of a sector being erased.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void BackupSector(EEPROM_TAddress_ Addr, word From, word To)
{
  word i;

  for (i = From; i < To; i = i + 2U) {
    BackupArray[i/2U] = *(word *far) (Addr + (i/2U)); /* save one sector to RAM */
  }
}

/*
** ===================================================================
**     Method      :  WriteBlock (component IntEEPROM)
**
**     Description :
**         The method writes the block of data to EEPROM memory.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static byte WriteBlock(EEPROM_TAddress Addr, word From, word To, const word* Data)
{
  byte err = 0U;
  word i;
  byte j;
  dword PhraseAddr;

  if(From == To) {
    return ERR_OK;
  }
  i = From;
  PhraseAddr = (dword)Addr;
  while(i < To) {
  /* FSTAT: ACCERR=1,FPVIOL=1 */
    FSTAT = 0x30U;                     /* Clear error flags */
    FCCOBIX = 0U;                      /* Clear index register */
    FCCOBHI = 0x11U;                   /* Program D-Flash command */
    FCCOBLO = (byte)(PhraseAddr >> 16U); /* High address word */
    FCCOBIX++;                         /* Shift index register */
    FCCOB = (word)PhraseAddr;          /* Low address word */
    for(j = 0U;j < 8U;j+=2U) {
      FCCOBIX++;                       /* Shift index register */
      FCCOB = *(const word*)(Data + (i/2U)); /* Load new data */
      i += 2U;
      if(i >= To) {break;}
    }
    FSTAT = 0x80U;                     /* Clear flag command buffer empty */
    while (FSTAT_CCIF == 0U) {}        /* Wait to command complete */
    if ((FSTAT & 0x30U) != 0U) {       /* Is protection violation or acces error detected ? */
      return ERR_NOTAVAIL;             /* If yes then error */
    }
    if (FSTAT_MGSTAT) {                /* Was attempt to write data to the given address errorneous? */
      err = 1U;                        /* If yes then mark an error */
    }
    PhraseAddr += 8U;
  }
  if(err != 0U) {
    return ERR_VALUE;                  /* If yes then error */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  EraseSectorInternal (component IntEEPROM)
**
**     Description :
**         The method erase a specific sector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static byte EraseSectorInternal(EEPROM_TAddress Addr)
{
  if (FSTAT_CCIF == 0U) {              /* Is command complete ? */
    return ERR_BUSY;                   /* If yes then error */
  }
  /* FSTAT: ACCERR=1,FPVIOL=1 */
  FSTAT = 0x30U;                       /* Clear error flags */
  FCCOBIX = 0U;                        /* Clear index register */
  FCCOBHI = 0x12U;                     /* Erase D-Flash sector command */
  FCCOBLO = (byte)(((dword)Addr) >> 16); /* High address word */
  FCCOBIX++;                           /* Shift index register */
  FCCOB = (word)(((dword)Addr) & 0xFFFFFFFEUL); /* Low address word aligned to word*/
  FSTAT = 0x80U;                       /* Clear flag command buffer empty */
  while (FSTAT_CCIF == 0U) {}          /* Wait to command complete */
  if ((FSTAT & 0x23U) != 0U) {         /* Is access error or other error detected ? */
    return ERR_NOTAVAIL;               /* If yes then error */
  }
  return ERR_OK;                       /* OK */
}
/*
** ===================================================================
**     Method      :  WriteWord (component IntEEPROM)
**
**     Description :
**         The method writes the word data to EEPROM memory.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static byte WriteWord(EEPROM_TAddress AddrRow,word Data16)
{
  if (FSTAT_CCIF == 0U) {              /* Is previous command in process ? */
    return ERR_BUSY;                   /* If yes then error */
  }
  /* FSTAT: ACCERR=1,FPVIOL=1 */
  FSTAT = 0x30U;                       /* Clear error flags */
  FCCOBIX = 0U;                        /* Clear index register */
  FCCOBHI = 0x11U;                     /* Program D-Flash command */
  FCCOBLO = (byte)(((dword)AddrRow) >> 16); /* High address word */
  FCCOBIX++;                           /* Shift index register */
  FCCOB = (word)((dword)AddrRow);      /* Low address word */
  FCCOBIX++;                           /* Shift index register */
  FCCOB = Data16;                      /* Load new data */
  FSTAT = 0x80U;                       /* Clear flag command complete */
  if ((FSTAT & 0x30U) != 0U) {         /* Is protection violation or acces error detected ? */
    return ERR_NOTAVAIL;               /* If yes then error */
  }
  while (!FSTAT_CCIF) {}               /* Wait for command completition */
  if (FSTAT_MGSTAT) {                  /* Was attempt to write data to the given address errorneous? */
    return ERR_VALUE;                  /* If yes then error */
  }
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  EEPROM_SetByte (component IntEEPROM)
**
**     Description :
**         This method writes a given byte to a specified address in
**         EEPROM. The method also sets address pointer for <SetActByte>
**         and <GetActByte> methods (applicable only if these methods
**         are enabled). The pointer is set to address passed as the
**         parameter.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Addr            - Address to EEPROM
**         Data            - Data to write
**     Returns     :
**         ---             - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_SPEED - the component does not work
**                           in the active speed mode 
**                           - ERR_BUSY - device is busy 
**                           - ERR_VALUE - verification of written data
**                           failed (read value does not match with
**                           written value) 
**                           - ERR_NOTAVAIL - other device-specific
**                           error 
**                           - ERR_RANGE - parameter Addr is out of range
** ===================================================================
*/
byte EEPROM_SetByte(EEPROM_TAddress Addr,byte Data)
{
  byte err;
  word Data16;
  EEPROM_TAddress SecAddr;             /* EEPROM Sector address */

  if(((dword)Addr < (dword)EEPROM_AREA_START) || ((dword)Addr > (dword)EEPROM_AREA_END)) { /* Is given address out of EEPROM area array ? */
    return ERR_RANGE;                  /* If yes then error */
  }
  if(!FSTAT_CCIF) {                    /* Is reading from EEPROM possible? */
    return ERR_BUSY;                   /* If no then error */
  }
  SecAddr = (EEPROM_TAddress)((dword)Addr & 0x00FFFFFEUL); /* Aligned word address */
  if (*((word *far)(SecAddr)) == 0xFFFFU) { /* Is the word erased? */
    if (((dword)Addr) & 1U) {          /* Not Aligned word ? */
      return(WriteWord(SecAddr, ((*SecAddr) & 0xFF00U) | Data));
    } else {
      return(WriteWord(Addr, ((word)Data << 8) | (*(((byte *far)Addr) + 1U)))); /* Aligned word ? */
    }
  } else {                             /* Is given address non-erased ? */
    SecAddr = (EEPROM_TAddress)((dword)Addr & 0x00FFFF00UL); /* Sector Aligned address */
    BackupSector(SecAddr, 0U, 0x0100U); /* Backup sector */
    Data16 = BackupArray[(((dword)Addr) % 0x0100U) / 2U]; /* Store new data to backup array*/
    if (((dword)Addr) & 1U) {          /* Not Aligned word ? */
      Data16 = (Data16 & 0xFF00U) | Data;
    } else {
      Data16 = ((word)Data << 8) | (Data16 & 0xFFU);
    }
    BackupArray[(((dword)Addr) % 0x0100U) / 2U] = Data16; /* Write new data to saved sector */
    err = EraseSectorInternal(Addr);   /* Erase sector */
    if(err != 0U) {
      return(err);                     /* Return error code if previous operation finished not correctly */
    }
    err = WriteBlock(SecAddr, 0U, 0x0100U,BackupArray); /* Restore sector */
    return(err);
  }
}

/*
** ===================================================================
**     Method      :  EEPROM_GetByte (component IntEEPROM)
**
**     Description :
**         This method reads a byte from a specified EEPROM address.
**         The method also sets address pointer for <SetActByte> and
**         <GetActByte> methods (applicable only if these methods are
**         enabled). The pointer is set to address passed as the
**         parameter.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Addr            - EEPROM Address
**       * Data            - A pointer to the returned 8-bit data
**     Returns     :
**         ---             - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_BUSY - device is busy 
**                           - ERR_RANGE - parameter Addr is out of range
** ===================================================================
*/
byte EEPROM_GetByte(EEPROM_TAddress Addr,byte *Data)
{
  if(((dword)Addr < (dword)EEPROM_AREA_START) || ((dword)Addr > (dword)EEPROM_AREA_END)) { /* Is given address out of EEPROM area array ? */
    return ERR_RANGE;                  /* If yes then error */
  }
  if(!FSTAT_CCIF) {                    /* Is reading from EEPROM possible? */
    return ERR_BUSY;                   /* If no then error */
  }
  *Data = *((byte *far)Addr);
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  EEPROM_Init (component IntEEPROM)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void EEPROM_Init(void)
{
}

/*lint -restore Enable MISRA rule (11.3,11.4) checking. */

/* END EEPROM. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
