/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : GPIOC.c
**     Project   : Project
**     Processor : MC9S12XEP100MAG
**     Component : Init_GPIO
**     Version   : Component 01.114, Driver 01.08, CPU db: 3.00.036
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2016/8/14, 15:02
**     Abstract  :
**          This file implements the General Purpose Input Output (C)
**          module initialization according to the Peripheral Initialization
**          settings, and defines interrupt service routines prototypes.
**
**     Settings  :
**          Component name                                 : GPIOC
**          Device                                         : C
**          Port control                                   : Entire I/O port
**
**          Port direction                                 : Output
**          Port output value                              : 0x18
**          Pull resistor                                  : no pull resistor
**          Open drain                                     : push-pull
**
**          Call Init method                               : yes
**     Contents  :
**         Init - void GPIOC_Init(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE GPIOC. */

#include "GPIOC.h"
/*
** ===================================================================
**     Method      :  GPIOC_Init (component Init_GPIO)
**
**     Description :
**         This method initializes registers of the GPIO module
**         according to this Peripheral Initialization settings. Call
**         this method in the user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void GPIOC_Init(void)
{
  /* PORTC: PC7=0,PC6=0,PC5=0,PC4=1,PC3=1,PC2=0,PC1=0,PC0=0 */
  setReg8(PORTC, 0x18U);                
  /* PUCR: PUPCE=0 */
  clrReg8Bits(PUCR, 0x04U);             
  /* DDRC: DDRC7=1,DDRC6=1,DDRC5=1,DDRC4=1,DDRC3=1,DDRC2=1,DDRC1=1,DDRC0=1 */
  setReg8(DDRC, 0xFFU);                 
}

/* END GPIOC. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
