/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : GPIOK.c
**     Project   : Project
**     Processor : MC9S12XEP100MAG
**     Component : Init_GPIO
**     Version   : Component 01.100, Driver 01.08, CPU db: 3.00.034
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2017/6/5, 13:25
**     Abstract  :
**          This file implements the General Purpose Input Output (K)
**          module initialization according to the Peripheral Initialization
**          settings, and defines interrupt service routines prototypes.
**
**     Settings  :
**          Component name                                 : GPIOK
**          Device                                         : K
**          Port control                                   : Individual pins
**
**          Used pins                                      :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       0             |  PK0_ADDR16_IQSTAT0
**                       1             |  PK1_ADDR17_IQSTAT1
**                       2             |  PK2_ADDR18_IQSTAT2
**                       3             |  PK3_ADDR19_IQSTAT3
**                       6             |  PK6_ADDR22_ACC2
**             ----------------------------------------------------
**
**          Pin0                                           : PK0_ADDR16_IQSTAT0
**            Direction                                    : Output
**            Output value                                 : 1
**            Pull resistor                                : no pull resistor
**            Open drain                                   : push-pull
**
**          Pin1                                           : PK1_ADDR17_IQSTAT1
**            Direction                                    : Output
**            Output value                                 : 0
**            Pull resistor                                : no pull resistor
**            Open drain                                   : push-pull
**
**          Pin2                                           : PK2_ADDR18_IQSTAT2
**            Direction                                    : Output
**            Output value                                 : 1
**            Pull resistor                                : no pull resistor
**            Open drain                                   : push-pull
**
**          Pin3                                           : PK3_ADDR19_IQSTAT3
**            Direction                                    : Output
**            Output value                                 : 0
**            Pull resistor                                : no pull resistor
**            Open drain                                   : push-pull
**
**          Pin6                                           : PK6_ADDR22_ACC2
**            Direction                                    : Output
**            Output value                                 : 1
**            Pull resistor                                : no initialization
**            Open drain                                   : push-pull
**
**          Call Init method                               : yes
**     Contents  :
**         Init - void GPIOK_Init(void);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE GPIOK. */

#include "GPIOK.h"
/*
** ===================================================================
**     Method      :  GPIOK_Init (component Init_GPIO)
**
**     Description :
**         This method initializes registers of the GPIO module
**         according to this Peripheral Initialization settings. Call
**         this method in the user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void GPIOK_Init(void)
{
  /* PORTK: PK6=1,PK3=0,PK2=1,PK1=0,PK0=1 */
  clrSetReg8Bits(PORTK, 0x0AU, 0x45U);  
  /* PUCR: PUPKE=0 */
  clrReg8Bits(PUCR, 0x80U);             
  /* DDRK: DDRK6=1,DDRK3=1,DDRK2=1,DDRK1=1,DDRK0=1 */
  setReg8Bits(DDRK, 0x4FU);             
}

/* END GPIOK. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
