/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : GPIOJ.c
**     Project   : Project
**     Processor : MC9S12XEP100MAG
**     Component : Init_GPIO
**     Version   : Component 01.114, Driver 01.08, CPU db: 3.00.036
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2016/8/14, 15:02
**     Abstract  :
**          This file implements the General Purpose Input Output (J)
**          module initialization according to the Peripheral Initialization
**          settings, and defines interrupt service routines prototypes.
**
**     Settings  :
**          Component name                                 : GPIOJ
**          Device                                         : J
**          Port control                                   : Individual pins
**
**          Used pins                                      :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       4             |  PJ4_KWJ4_SDA1_CS0
**                       5             |  PJ5_KWJ5_SCL1_CS2
**                       6             |  PJ6_KWJ6_RxCAN4_SDA0_RxCAN0
**                       7             |  PJ7_KWJ7_TxCAN4_SCL0_TxCAN0
**             ----------------------------------------------------
**
**          Pin4                                           : PJ4_KWJ4_SDA1_CS0
**            Direction                                    : Input
**            Output value                                 : 0
**            Pull resistor                                : pull down
**            Open drain                                   : push-pull
**
**          Pin5                                           : PJ5_KWJ5_SCL1_CS2
**            Direction                                    : Input
**            Output value                                 : 0
**            Pull resistor                                : pull down
**            Open drain                                   : push-pull
**
**          Pin6                                           : PJ6_KWJ6_RxCAN4_SDA0_RxCAN0
**            Direction                                    : Input
**            Output value                                 : 0
**            Pull resistor                                : no pull resistor
**            Open drain                                   : push-pull
**
**          Pin7                                           : PJ7_KWJ7_TxCAN4_SCL0_TxCAN0
**            Direction                                    : Input
**            Output value                                 : 0
**            Pull resistor                                : no pull resistor
**            Open drain                                   : push-pull
**
**          Call Init method                               : yes
**     Contents  :
**         Init - void GPIOJ_Init(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE GPIOJ. */

#include "GPIOJ.h"
/*
** ###################################################################
**
**  The interrupt service routine(s) must be implemented
**  by user in one of the following user modules.
**
**  If the "Generate ISR" option is enabled, Processor Expert generates
**  ISR templates in the CPU event module.
**
**  User modules:
**      Project.c
**      Events.c
**
** ###################################################################
#pragma CODE_SEG __NEAR_SEG NON_BANKED
ISR(CapPJ)
        {
        // NOTE: The routine should include the following actions to obtain
        //       correct functionality of the hardware.
        //
        //      To clear interrupt flag 1 must be written to a bit, which correspods
        //      to pin which detected an active edge.
        //      Example: PIFJ = 0xFF;
        }
#pragma CODE_SEG DEFAULT
*/
/*
** ===================================================================
**     Method      :  GPIOJ_Init (component Init_GPIO)
**
**     Description :
**         This method initializes registers of the GPIO module
**         according to this Peripheral Initialization settings. Call
**         this method in the user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void GPIOJ_Init(void)
{
    /* Disable interrupts */
  /* PIEJ: PIEJ7=0,PIEJ6=0,PIEJ5=0,PIEJ4=0,PIEJ2=0,PIEJ1=0,PIEJ0=0 */
  clrReg8Bits(PIEJ, 0xF7U);             
    /* Clear interrupt flags */
  /* PIFJ: PIFJ7=1,PIFJ6=1,PIFJ5=1,PIFJ4=1,PIFJ3=0,PIFJ2=1,PIFJ1=1,PIFJ0=1 */
  setReg8(PIFJ, 0xF7U);                 
  /* PTJ: PTJ7=0,PTJ6=0,PTJ5=0,PTJ4=0 */
  clrReg8Bits(PTJ, 0xF0U);              
  /* PPSJ: PPSJ5=1,PPSJ4=1 */
  setReg8Bits(PPSJ, 0x30U);             
  /* PERJ: PERJ7=0,PERJ6=0,PERJ5=1,PERJ4=1 */
  clrSetReg8Bits(PERJ, 0xC0U, 0x30U);   
  /* DDRJ: DDRJ7=0,DDRJ6=0,DDRJ5=0,DDRJ4=0 */
  clrReg8Bits(DDRJ, 0xF0U);             
  /* PIEJ: PIEJ7=0,PIEJ6=0,PIEJ5=1,PIEJ4=1,PIEJ3=0,PIEJ2=0,PIEJ1=0,PIEJ0=0 */
  setReg8(PIEJ, 0x30U);                 
}

/* END GPIOJ. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
