/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : GPIOH.c
**     Project   : Project
**     Processor : MC9S12XEP100MAG
**     Component : Init_GPIO
**     Version   : Component 01.114, Driver 01.08, CPU db: 3.00.036
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2016/8/14, 15:02
**     Abstract  :
**          This file implements the General Purpose Input Output (H)
**          module initialization according to the Peripheral Initialization
**          settings, and defines interrupt service routines prototypes.
**
**     Settings  :
**          Component name                                 : GPIOH
**          Device                                         : H
**          Port control                                   : Individual pins
**
**          Used pins                                      :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       0             |  PH0_KWH0_MISO1_RxD6
**                       1             |  PH1_KWH1_MOSI1_TxD6
**                       2             |  PH2_KWH2_SCK1_RxD7
**                       3             |  PH3_KWH3_SS1_TxD7
**                       7             |  PH7_KWH7_SS2_TxD5
**             ----------------------------------------------------
**
**          Pin0                                           : PH0_KWH0_MISO1_RxD6
**            Direction                                    : Output
**            Output value                                 : 0
**            Pull resistor                                : no initialization
**            Open drain                                   : push-pull
**
**          Pin1                                           : PH1_KWH1_MOSI1_TxD6
**            Direction                                    : Output
**            Output value                                 : 0
**            Pull resistor                                : no initialization
**            Open drain                                   : push-pull
**
**          Pin2                                           : PH2_KWH2_SCK1_RxD7
**            Direction                                    : Input
**            Output value                                 : 0
**            Pull resistor                                : pull down
**            Open drain                                   : push-pull
**
**          Pin3                                           : PH3_KWH3_SS1_TxD7
**            Direction                                    : Input
**            Output value                                 : 0
**            Pull resistor                                : pull down
**            Open drain                                   : push-pull
**
**          Pin7                                           : PH7_KWH7_SS2_TxD5
**            Direction                                    : Output
**            Output value                                 : 1
**            Pull resistor                                : no initialization
**            Open drain                                   : push-pull
**
**          Call Init method                               : yes
**     Contents  :
**         Init - void GPIOH_Init(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE GPIOH. */

#include "GPIOH.h"
/*
** ###################################################################
**
**  The interrupt service routine(s) must be implemented
**  by user in one of the following user modules.
**
**  If the "Generate ISR" option is enabled, Processor Expert generates
**  ISR templates in the CPU event module.
**
**  User modules:
**      Project.c
**      Events.c
**
** ###################################################################
#pragma CODE_SEG __NEAR_SEG NON_BANKED
ISR(CapPH)
        {
        // NOTE: The routine should include the following actions to obtain
        //       correct functionality of the hardware.
        //
        //      To clear interrupt flag 1 must be written to a bit, which correspods
        //      to pin which detected an active edge.
        //      Example: PIFH = 0xFF;
        }
#pragma CODE_SEG DEFAULT
*/
/*
** ===================================================================
**     Method      :  GPIOH_Init (component Init_GPIO)
**
**     Description :
**         This method initializes registers of the GPIO module
**         according to this Peripheral Initialization settings. Call
**         this method in the user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void GPIOH_Init(void)
{
    /* Disable interrupts */
  /* PIEH: PIEH7=0,PIEH6=0,PIEH5=0,PIEH4=0,PIEH3=0,PIEH2=0,PIEH1=0,PIEH0=0 */
  setReg8(PIEH, 0x00U);                 
    /* Clear interrupt flags */
  /* PIFH: PIFH7=1,PIFH6=1,PIFH5=1,PIFH4=1,PIFH3=1,PIFH2=1,PIFH1=1,PIFH0=1 */
  setReg8(PIFH, 0xFFU);                 
  /* PTH: PTH7=1,PTH3=0,PTH2=0,PTH1=0,PTH0=0 */
  clrSetReg8Bits(PTH, 0x0FU, 0x80U);    
  /* PPSH: PPSH3=1,PPSH2=1 */
  setReg8Bits(PPSH, 0x0CU);             
  /* PERH: PERH3=1,PERH2=1 */
  setReg8Bits(PERH, 0x0CU);             
  /* DDRH: DDRH7=1,DDRH3=0,DDRH2=0,DDRH1=1,DDRH0=1 */
  clrSetReg8Bits(DDRH, 0x0CU, 0x83U);   
  /* PIEH: PIEH7=0,PIEH6=0,PIEH5=0,PIEH4=0,PIEH3=1,PIEH2=1,PIEH1=0,PIEH0=0 */
  setReg8(PIEH, 0x0CU);                 
}

/* END GPIOH. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
