/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : GPIOH.h
**     Project   : Project
**     Processor : MC9S12XEP100MAG
**     Component : Init_GPIO
**     Version   : Component 01.114, Driver 01.08, CPU db: 3.00.036
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2016/8/14, 15:02
**     Abstract  :
**          This file implements the General Purpose Input Output (H)
**          module initialization according to the Peripheral Initialization
**          settings, and defines interrupt service routines prototypes.
**
**     Settings  :
**          Component name                                 : GPIOH
**          Device                                         : H
**          Port control                                   : Individual pins
**
**          Used pins                                      :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       0             |  PH0_KWH0_MISO1_RxD6
**                       1             |  PH1_KWH1_MOSI1_TxD6
**                       2             |  PH2_KWH2_SCK1_RxD7
**                       3             |  PH3_KWH3_SS1_TxD7
**                       7             |  PH7_KWH7_SS2_TxD5
**             ----------------------------------------------------
**
**          Pin0                                           : PH0_KWH0_MISO1_RxD6
**            Direction                                    : Output
**            Output value                                 : 0
**            Pull resistor                                : no initialization
**            Open drain                                   : push-pull
**
**          Pin1                                           : PH1_KWH1_MOSI1_TxD6
**            Direction                                    : Output
**            Output value                                 : 0
**            Pull resistor                                : no initialization
**            Open drain                                   : push-pull
**
**          Pin2                                           : PH2_KWH2_SCK1_RxD7
**            Direction                                    : Input
**            Output value                                 : 0
**            Pull resistor                                : pull down
**            Open drain                                   : push-pull
**
**          Pin3                                           : PH3_KWH3_SS1_TxD7
**            Direction                                    : Input
**            Output value                                 : 0
**            Pull resistor                                : pull down
**            Open drain                                   : push-pull
**
**          Pin7                                           : PH7_KWH7_SS2_TxD5
**            Direction                                    : Output
**            Output value                                 : 1
**            Pull resistor                                : no initialization
**            Open drain                                   : push-pull
**
**          Call Init method                               : yes
**     Contents  :
**         Init - void GPIOH_Init(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __GPIOH
#define __GPIOH

/* MODULE GPIOH. */

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited components */

#include "Cpu.h"


void GPIOH_Init(void);
/*
** ===================================================================
**     Method      :  GPIOH_Init (component Init_GPIO)
**
**     Description :
**         This method initializes registers of the GPIO module
**         according to this Peripheral Initialization settings. Call
**         this method in the user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

/*
** ===================================================================
** The interrupt service routine must be implemented by user in one
** of the user modules (see GPIOH.c file for more information).
** ===================================================================
*/
#pragma CODE_SEG __NEAR_SEG NON_BANKED
__interrupt void CapPH(void);
#pragma CODE_SEG DEFAULT
/* END GPIOH. */
#endif /* ifndef __GPIOH */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
