/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : GPIOB.c
**     Project   : Project
**     Processor : MC9S12XEP100MAG
**     Component : Init_GPIO
**     Version   : Component 01.114, Driver 01.08, CPU db: 3.00.036
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2016/8/14, 15:02
**     Abstract  :
**          This file implements the General Purpose Input Output (B)
**          module initialization according to the Peripheral Initialization
**          settings, and defines interrupt service routines prototypes.
**
**     Settings  :
**          Component name                                 : GPIOB
**          Device                                         : B
**          Port control                                   : Individual pins
**
**          Used pins                                      :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       0             |  PB0_ADDR0_IVD0_UDS
**                       1             |  PB1_ADDR1_IVD1
**                       2             |  PB2_ADDR2_IVD2
**                       4             |  PB4_ADDR4_IVD4
**                       5             |  PB5_ADDR5_IVD5
**                       6             |  PB6_ADDR6_IVD6
**                       7             |  PB7_ADDR7_IVD7
**             ----------------------------------------------------
**
**          Pin0                                           : PB0_ADDR0_IVD0_UDS
**            Direction                                    : Input
**            Output value                                 : 0
**            Pull resistor                                : no pull resistor
**            Open drain                                   : push-pull
**
**          Pin1                                           : PB1_ADDR1_IVD1
**            Direction                                    : Output
**            Output value                                 : 0
**            Pull resistor                                : no pull resistor
**            Open drain                                   : push-pull
**
**          Pin2                                           : PB2_ADDR2_IVD2
**            Direction                                    : Output
**            Output value                                 : 0
**            Pull resistor                                : no initialization
**            Open drain                                   : push-pull
**
**          Pin4                                           : PB4_ADDR4_IVD4
**            Direction                                    : Output
**            Output value                                 : 0
**            Pull resistor                                : no pull resistor
**            Open drain                                   : push-pull
**
**          Pin5                                           : PB5_ADDR5_IVD5
**            Direction                                    : Output
**            Output value                                 : 0
**            Pull resistor                                : no pull resistor
**            Open drain                                   : push-pull
**
**          Pin6                                           : PB6_ADDR6_IVD6
**            Direction                                    : Output
**            Output value                                 : 0
**            Pull resistor                                : no pull resistor
**            Open drain                                   : push-pull
**
**          Pin7                                           : PB7_ADDR7_IVD7
**            Direction                                    : Input
**            Output value                                 : 0
**            Pull resistor                                : no pull resistor
**            Open drain                                   : push-pull
**
**          Call Init method                               : yes
**     Contents  :
**         Init - void GPIOB_Init(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE GPIOB. */

#include "GPIOB.h"
/*
** ===================================================================
**     Method      :  GPIOB_Init (component Init_GPIO)
**
**     Description :
**         This method initializes registers of the GPIO module
**         according to this Peripheral Initialization settings. Call
**         this method in the user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void GPIOB_Init(void)
{
  /* PORTB: PB7=0,PB6=0,PB5=0,PB4=0,PB2=0,PB1=0,PB0=0 */
  clrReg8Bits(PORTB, 0xF7U);            
  /* PUCR: PUPBE=0 */
  clrReg8Bits(PUCR, 0x02U);             
  /* DDRB: DDRB7=0,DDRB6=1,DDRB5=1,DDRB4=1,DDRB2=1,DDRB1=1,DDRB0=0 */
  clrSetReg8Bits(DDRB, 0x81U, 0x76U);   
}

/* END GPIOB. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
