/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : GPIOJ.h
**     Project   : Project
**     Processor : MC9S12XEP100MAG
**     Component : Init_GPIO
**     Version   : Component 01.114, Driver 01.08, CPU db: 3.00.036
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2016/8/14, 15:02
**     Abstract  :
**          This file implements the General Purpose Input Output (J)
**          module initialization according to the Peripheral Initialization
**          settings, and defines interrupt service routines prototypes.
**
**     Settings  :
**          Component name                                 : GPIOJ
**          Device                                         : J
**          Port control                                   : Individual pins
**
**          Used pins                                      :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       4             |  PJ4_KWJ4_SDA1_CS0
**                       5             |  PJ5_KWJ5_SCL1_CS2
**                       6             |  PJ6_KWJ6_RxCAN4_SDA0_RxCAN0
**                       7             |  PJ7_KWJ7_TxCAN4_SCL0_TxCAN0
**             ----------------------------------------------------
**
**          Pin4                                           : PJ4_KWJ4_SDA1_CS0
**            Direction                                    : Input
**            Output value                                 : 0
**            Pull resistor                                : pull down
**            Open drain                                   : push-pull
**
**          Pin5                                           : PJ5_KWJ5_SCL1_CS2
**            Direction                                    : Input
**            Output value                                 : 0
**            Pull resistor                                : pull down
**            Open drain                                   : push-pull
**
**          Pin6                                           : PJ6_KWJ6_RxCAN4_SDA0_RxCAN0
**            Direction                                    : Input
**            Output value                                 : 0
**            Pull resistor                                : no pull resistor
**            Open drain                                   : push-pull
**
**          Pin7                                           : PJ7_KWJ7_TxCAN4_SCL0_TxCAN0
**            Direction                                    : Input
**            Output value                                 : 0
**            Pull resistor                                : no pull resistor
**            Open drain                                   : push-pull
**
**          Call Init method                               : yes
**     Contents  :
**         Init - void GPIOJ_Init(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __GPIOJ
#define __GPIOJ

/* MODULE GPIOJ. */

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited components */

#include "Cpu.h"


void GPIOJ_Init(void);
/*
** ===================================================================
**     Method      :  GPIOJ_Init (component Init_GPIO)
**
**     Description :
**         This method initializes registers of the GPIO module
**         according to this Peripheral Initialization settings. Call
**         this method in the user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

/*
** ===================================================================
** The interrupt service routine must be implemented by user in one
** of the user modules (see GPIOJ.c file for more information).
** ===================================================================
*/
#pragma CODE_SEG __NEAR_SEG NON_BANKED
__interrupt void CapPJ(void);
#pragma CODE_SEG DEFAULT
/* END GPIOJ. */
#endif /* ifndef __GPIOJ */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
