/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : GPIOE.h
**     Project   : Project
**     Processor : MC9S12XEP100MAG
**     Component : Init_GPIO
**     Version   : Component 01.114, Driver 01.08, CPU db: 3.00.036
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2016/8/14, 15:02
**     Abstract  :
**          This file implements the General Purpose Input Output (E)
**          module initialization according to the Peripheral Initialization
**          settings, and defines interrupt service routines prototypes.
**
**     Settings  :
**          Component name                                 : GPIOE
**          Device                                         : E
**          Port control                                   : Individual pins
**
**          Used pins                                      :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       2             |  PE2_RW_WE
**                       3             |  PE3_LSTRB_LDS_EROMCTL
**             ----------------------------------------------------
**
**          Pin2                                           : PE2_RW_WE
**            Direction                                    : Output
**            Output value                                 : 0
**            Pull resistor                                : no pull resistor
**            Open drain                                   : push-pull
**
**          Pin3                                           : PE3_LSTRB_LDS_EROMCTL
**            Direction                                    : Output
**            Output value                                 : 0
**            Pull resistor                                : no pull resistor
**            Open drain                                   : push-pull
**
**          Call Init method                               : yes
**     Contents  :
**         Init - void GPIOE_Init(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __GPIOE
#define __GPIOE

/* MODULE GPIOE. */

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited components */

#include "Cpu.h"


void GPIOE_Init(void);
/*
** ===================================================================
**     Method      :  GPIOE_Init (component Init_GPIO)
**
**     Description :
**         This method initializes registers of the GPIO module
**         according to this Peripheral Initialization settings. Call
**         this method in the user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

/* END GPIOE. */
#endif /* ifndef __GPIOE */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
