/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : SPI2.c
**     Project   : Project
**     Processor : MC9S12XEP100MAG
**     Component : SynchroMaster
**     Version   : Component 02.341, Driver 01.20, CPU db: 3.00.034
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2017/5/26, 12:01
**     Abstract  :
**         This component "SynchroMaster" implements MASTER part of synchronous
**         serial master-slave communication.
**     Settings  :
**         Synchro type                : MASTER
**
**         Serial channel              : SPI2
**
**         Protocol
**             Init baud rate          : 1us
**             Clock edge              : rising
**             Width                   : 8 bits
**             Empty character         : 0
**             Empty char. on input    : RECEIVED
**
**         Registers
**             Input buffer            : SPI2DR    [$00FC]
**             Output buffer           : SPI2DR    [$00FC]
**             Control register        : SPI2CR1   [$00F8]
**             Mode register           : SPI2CR2   [$00F9]
**             Baud setting reg.       : SPI2BR    [$00FA]
**
**             Priority                : 
**
**             Priority                : 
**
**         Used pins                   :
**         ----------------------------------------------------------
**              Function    | On package |    Name
**         ----------------------------------------------------------
**               Input      |     47     |  PH4_KWH4_MISO2_RxD4
**               Output     |     46     |  PH5_KWH5_MOSI2_TxD4
**               Clock      |     45     |  PH6_KWH6_SCK2_RxD5
**         ----------------------------------------------------------
**
**     Contents  :
**         RecvChar        - byte SPI2_RecvChar(SPI2_TComData *Chr);
**         SendChar        - byte SPI2_SendChar(SPI2_TComData Chr);
**         GetCharsInRxBuf - word SPI2_GetCharsInRxBuf(void);
**         GetCharsInTxBuf - word SPI2_GetCharsInTxBuf(void);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/


/* MODULE SPI2. */

#include "SPI2.h"
#include "AD0.h"
#include "AD1.h"
#include "GPIOA.h"
#include "GPIOB.h"
#include "GPIOC.h"
#include "GPIOD.h"
#include "GPIOE.h"
#include "GPIOH.h"
#include "GPIOJ.h"
#include "GPIOK.h"
#include "GPIOS.h"
#include "ECT.h"
#include "Wdg.h"
#include "CAN0.h"
#include "CAN1.h"
#include "TickTimer.h"
#include "TimeStamp.h"
#include "PWM0.h"
#include "PWM1.h"
#include "PWM2.h"
#include "PWM3.h"
#include "PWM4.h"
#include "PWM5.h"
#include "PWM6.h"
#include "PWM7.h"
#include "Flash.h"
#include "EEPROM.h"
#include "CAN2.h"
#include "CAN3.h"

#pragma DATA_SEG SPI2_DATA             /* Select data segment "SPI2_DATA" */
#pragma CODE_SEG SPI2_CODE


#define OVERRUN_ERR      0x01U         /* Overrun error flag bit   */
#define CHAR_IN_RX       0x08U         /* Char is in RX buffer     */
#define FULL_TX          0x10U         /* Full transmit buffer     */
#define RUNINT_FROM_TX   0x20U         /* Interrupt is in progress */
#define FULL_RX          0x40U         /* Full receive buffer      */


/*
** ===================================================================
**     Method      :  SPI2_RecvChar (component SynchroMaster)
**
**     Description :
**         If any data is received, this method returns one character,
**         otherwise it returns an error code (it does not wait for
**         data). 
**         For information about SW overrun behavior please see
**         <General info page>.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Chr             - A pointer to the received character
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK - The valid data is received.
**                           ERR_SPEED - This device does not work in
**                           the active speed mode.
**                           ERR_RXEMPTY - No data in receiver.
**                           ERR_OVERRUN - Overrun error was detected
**                           from the last char or block received. In
**                           polling mode, this error code is returned
**                           only when the hardware supports detection
**                           of the overrun error. The valid data is
**                           also received.
**                           ERR_FAULT - Fault error was detected from
**                           the last char or block received. In the
**                           polling mode the ERR_FAULT is return until
**                           the user clear the fault flag bit, but in
**                           the interrupt mode ERR_FAULT is returned
**                           only once after the fault error occured.
**                           This error is supported only on the CPUs
**                           supports the faul mode function - where
**                           <Fault mode> property is available.
** ===================================================================
*/
byte SPI2_RecvChar(SPI2_TComData *Chr)
{
  if ((SPI2SR & SPI2SR_SPIF_MASK) == 0U) { /* Is receive buffer empty? */
    return ERR_RXEMPTY;                /* If yes then error is returned */
  }
  *Chr = SPI2DRL;                      /* Read data from receiver */
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  SPI2_SendChar (component SynchroMaster)
**
**     Description :
**         Sends one character to the channel.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Chr             - Character to send
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - Device is disabled (only if
**                           output DMA is supported and enabled)
**                           ERR_TXFULL - Transmitter is full
** ===================================================================
*/
byte SPI2_SendChar(SPI2_TComData Chr)
{
  if (SPI2SR_SPTEF == 0U) {            /* Is last character send? */
    return ERR_TXFULL;                 /* If no then return error */
  }
  SPI2DRL = Chr;                       /* Send character */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  SPI2_GetCharsInRxBuf (component SynchroMaster)
**
**     Description :
**         Returns the number of characters in the input buffer.
**         Note: If the Interrupt service is disabled, and the Ignore
**         empty character is set to yes, and a character has been
**         received, then this method returns 1 although it was an
**         empty character.
**     Parameters  : None
**     Returns     :
**         ---             - Number of characters in the input buffer.
** ===================================================================
*/
/*
word SPI2_GetCharsInRxBuf(void)

**      This method is implemented as a macro. See header module. **
*/

/*
** ===================================================================
**     Method      :  SPI2_GetCharsInTxBuf (component SynchroMaster)
**
**     Description :
**         Returns the number of characters in the output buffer.
**     Parameters  : None
**     Returns     :
**         ---             - Number of characters in the output buffer.
** ===================================================================
*/
/*
word SPI2_GetCharsInTxBuf(void)

**      This method is implemented as a macro. See header module. **
*/

/*
** ===================================================================
**     Method      :  SPI2_Init (component SynchroMaster)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void SPI2_Init(void)
{
  /* SPI2CR1: SPIE=0,SPE=0,SPTIE=0,MSTR=0,CPOL=0,CPHA=1,SSOE=0,LSBFE=0 */
  SPI2CR1 = 0x04U;                     /* Reset the device register */
  (void)SPI2SR;                        /* Read the status register */
  (void)SPI2DRL;                       /* Read the device register */
  /* SPI2BR: ??=0,SPPR2=1,SPPR1=0,SPPR0=0,??=0,SPR2=0,SPR1=1,SPR0=0 */
  SPI2BR = 0x42U;                      /* Set the baud rate register */
  /* SPI2CR2: ??=0,XFRW=0,??=0,MODFEN=0,BIDIROE=0,??=0,SPISWAI=0,SPC0=0 */
  SPI2CR2 = 0x00U;                     /* Set control register 2 */
  /* SPI2CR1: SPIE=0,SPE=1,SPTIE=0,MSTR=1,CPOL=0,CPHA=1,SSOE=0,LSBFE=0 */
  SPI2CR1 = 0x54U;                     /* Set control register 1 */
}


/* END SPI2. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
