/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : TickTimer.c
**     Project   : Project
**     Processor : MC9S12XEP100MAG
**     Component : Init_API
**     Version   : Component 01.101, Driver 01.07, CPU db: 3.00.036
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2016/8/14, 15:02
**     Abstract  :
**          This file implements the API (API) module 
**          initialization according to the Peripheral Initialization 
**          Component settings, and defines interrupt service routines prototypes.
**          The Autonomous periodical Interrupt module can generate
**          periodical interrupts independent of the clock source of 
**          the MCU. To enable the timer, the bit APIFE needs to be 
**          set. The API timer is either clocked by a trimmable 
**          internal RC oscillator or the bus clock. Timer operation
**          will freeze when MCU clock source is selected and bus clock 
**          is turned off. The clock source can be selected with bit
**          APICLK. As soon as the configured timeout period of the API 
**          has elapsed, the APIF bit is set. An interrupt, indicated by 
**          flag APIF = 1, is triggered if interrupt enable bit APIE = 1.
**     Settings  :
**          Component name                                 : TickTimer
**          Device                                         : API
**          Settings                                       : 
**            Clock settings                               : 
**              Clock select                               : Bus clock
**              Period rate                                : 19999
**              Prescaler                                  : 40000
**              Period                                     : 1 ms
**            Trim settings                                : 
**              Period increase                            : no
**              Period decrease value                      : 0
**          Pins                                           : 
**            External Access                              : Disabled
**          Interrupts                                     : 
**            Interrupt                                    : Vapi
**            API Interrupt                                : Enabled
**            Priority                                     : 4
**            ISR name                                     : vPortTickInterrupt
**          Initialization                                 : 
**            Call Init method                             : no
**            Enable module                                : yes
**     Contents  :
**         Init - void TickTimer_Init(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE TickTimer. */

#include "TickTimer.h"

/*
** ###################################################################
**
**  The interrupt service routine(s) must be implemented
**  by user in one of the following user modules.
**
**  If the "Generate ISR" option is enabled, Processor Expert generates
**  ISR templates in the CPU event module.
**
**  User modules:
**      Project.c
**      Events.c
**
** ###################################################################
#pragma CODE_SEG __NEAR_SEG NON_BANKED
ISR(vPortTickInterrupt)
{
  // NOTE: The routine should include the following actions to obtain
  //       correct functionality of the hardware.
  //
  //       API interrupt request flag (APIF bit) must be set to 1 to
  //       clear the interrupt request.
  //       HCS12  Example: CPMUAPICTL_APIF = 1;
  //       HCS12X Example: VREGAPICL_APIF = 1;
}
#pragma CODE_SEG DEFAULT
*/
/*
** ===================================================================
**     Method      :  TickTimer_Init (component Init_API)
**
**     Description :
**         This method initializes registers of the API module
**         according to this Peripheral Initialization settings. Call
**         this method in the user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void TickTimer_Init(void)
{
  /* VREGAPICL: APICLK=0,??=0,??=0,APIES=0,APIEA=0,APIFE=0,APIE=0,APIF=0 */
  setReg8(VREGAPICL, 0x00U);            
  /* VREGAPIR: APIR15=0,APIR14=1,APIR13=0,APIR12=0,APIR11=1,APIR10=1,APIR9=1,APIR8=0,APIR7=0,APIR6=0,APIR5=0,APIR4=1,APIR3=1,APIR2=1,APIR1=1,APIR0=1 */
  setReg16(VREGAPIR, 0x4E1FU);          
  /* VREGAPITR: APITR5=0,APITR4=0,APITR3=0,APITR2=0,APITR1=0,APITR0=0,??=0,??=0 */
  setReg8(VREGAPITR, 0x00U);            
  /* VREGAPICL: APICLK=1,APIE=1,APIF=1 */
  setReg8Bits(VREGAPICL, 0x83U);        
  /* VREGAPICL: APIFE=1 */
  setReg8Bits(VREGAPICL, 0x04U);        
}

/* END TickTimer. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
