/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : TickTimer.h
**     Project   : Project
**     Processor : MC9S12XEP100MAG
**     Component : Init_API
**     Version   : Component 01.101, Driver 01.07, CPU db: 3.00.036
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2016/8/14, 15:02
**     Abstract  :
**          This file implements the API (API) module 
**          initialization according to the Peripheral Initialization 
**          Component settings, and defines interrupt service routines prototypes.
**          The Autonomous periodical Interrupt module can generate
**          periodical interrupts independent of the clock source of 
**          the MCU. To enable the timer, the bit APIFE needs to be 
**          set. The API timer is either clocked by a trimmable 
**          internal RC oscillator or the bus clock. Timer operation
**          will freeze when MCU clock source is selected and bus clock 
**          is turned off. The clock source can be selected with bit
**          APICLK. As soon as the configured timeout period of the API 
**          has elapsed, the APIF bit is set. An interrupt, indicated by 
**          flag APIF = 1, is triggered if interrupt enable bit APIE = 1.
**     Settings  :
**          Component name                                 : TickTimer
**          Device                                         : API
**          Settings                                       : 
**            Clock settings                               : 
**              Clock select                               : Bus clock
**              Period rate                                : 19999
**              Prescaler                                  : 40000
**              Period                                     : 1 ms
**            Trim settings                                : 
**              Period increase                            : no
**              Period decrease value                      : 0
**          Pins                                           : 
**            External Access                              : Disabled
**          Interrupts                                     : 
**            Interrupt                                    : Vapi
**            API Interrupt                                : Enabled
**            Priority                                     : 4
**            ISR name                                     : vPortTickInterrupt
**          Initialization                                 : 
**            Call Init method                             : no
**            Enable module                                : yes
**     Contents  :
**         Init - void TickTimer_Init(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __TickTimer
#define __TickTimer

/* MODULE TickTimer. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited components */

#include "Cpu.h"




void TickTimer_Init(void);
/*
** ===================================================================
**     Method      :  TickTimer_Init (component Init_API)
**
**     Description :
**         This method initializes registers of the API module
**         according to this Peripheral Initialization settings. Call
**         this method in the user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

/*
** ===================================================================
** The interrupt service routine must be implemented by user in one
** of the user modules (see TickTimer.c file for more information).
** ===================================================================
*/
#pragma CODE_SEG __NEAR_SEG NON_BANKED
__interrupt void vPortTickInterrupt(void);
#pragma CODE_SEG DEFAULT
/* END TickTimer. */

#endif
/* ifndef __TickTimer */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
