/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : TimeStamp.h
**     Project   : Project
**     Processor : MC9S12XEP100MAG
**     Component : Init_PIT
**     Version   : Component 01.124, Driver 01.09, CPU db: 3.00.036
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2016/8/16, 13:49
**     Abstract  :
**          This file implements the PIT module initialization
**          according to the Peripheral Initialization settings,
**          and defines interrupt service routines prototypes.
**          The period interrupt timer (PIT) is an array of 24-bit
**          timers that can be used to trigger peripheral modules
**          or raise periodic interrupts.
**          The PIT includes these features:
**          - Four timers implemented as modulus down-counters with
**            independent time-out periods.
**          - Time-out periods selectable between 1 and 224 bus clock
**            cycles. Time-out equals m*n bus clock cycles with
**            1 <= m >= 256 and 1 <= n >= 65536.
**          - Timers that can be enabled individually.
**          - Four time-out interrupts.
**          - Four time-out trigger output signals available to trigger
**            peripheral modules.
**          - Start of timer channels can be aligned to each other.
**     Settings  :
**          Component name                                 : TimeStamp
**          PIT device                                     : PIT
**          Settings                                       : 
**            Clock settings                               : 
**              Micro Timer 0 load register                : 39
**              Micro Timer 1 load register                : 199
**              Frequency of the Micro Timer 0             : 1 MHz
**              Frequency of the Micro Timer 1             : 200 kHz
**            Stop in wait mode                            : no
**            Stop in freeze mode                          : no
**          Channels                                       : 3
**            Channel                                      : 
**              Device                                     : PIT2
**              Enable Timer                               : yes
**              Timer is connected to                      : Micro Timer 0
**              Timer Load register                        : FFFF
**              Frequency of Timer                         : 15.258 Hz
**              Interrupt                                  : 
**                Timer out interrupt                      : Enabled
**                Interrupt                                : Vpit2
**                Priority                                 : 4
**                ISR name                                 : TimeStampInc
**            Channel                                      : 
**              Device                                     : PIT1
**              Enable Timer                               : yes
**              Timer is connected to                      : Micro Timer 1
**              Timer Load register                        : 19999
**              Frequency of Timer                         : 10 Hz
**              Interrupt                                  : 
**                Timer out interrupt                      : Enabled
**                Interrupt                                : Vpit1
**                Priority                                 : 4
**                ISR name                                 : PIT1_100MS
**            Channel                                      : 
**              Device                                     : PIT0
**              Enable Timer                               : no
**              Timer is connected to                      : Micro Timer 1
**              Timer Load register                        : 99
**              Frequency of Timer                         : 2 kHz
**              Interrupt                                  : 
**                Timer out interrupt                      : Disabled
**                Interrupt                                : Vpit0
**                Priority                                 : 4
**                ISR name                                 : 
**          Initialization                                 : 
**            Call Init method                             : yes
**            PIT periphery                                : Enabled
**     Contents  :
**         Init - void TimeStamp_Init(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __TimeStamp
#define __TimeStamp

/* MODULE TimeStamp. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited components */

#include "Cpu.h"

void TimeStamp_Init(void);
/*
** ===================================================================
**     Method      :  TimeStamp_Init (component Init_PIT)
**
**     Description :
**         This method initializes registers of the TIM module
**         according to this Peripheral Initialization settings. Call
**         this method in user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

/*
** ===================================================================
** The interrupt service routine must be implemented by user in one
** of the user modules (see TimeStamp.c file for more information).
** ===================================================================
*/
#pragma CODE_SEG __NEAR_SEG NON_BANKED
__interrupt void TimeStampInc(void);
__interrupt void PIT1_100MS(void);
#pragma CODE_SEG DEFAULT
/* END TimeStamp. */

#endif
/* ifndef __TimeStamp */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
