/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : TimeStamp.c
**     Project   : Project
**     Processor : MC9S12XEP100MAG
**     Component : Init_PIT
**     Version   : Component 01.124, Driver 01.09, CPU db: 3.00.036
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2016/8/16, 13:49
**     Abstract  :
**          This file implements the PIT module initialization
**          according to the Peripheral Initialization settings,
**          and defines interrupt service routines prototypes.
**          The period interrupt timer (PIT) is an array of 24-bit
**          timers that can be used to trigger peripheral modules
**          or raise periodic interrupts.
**          The PIT includes these features:
**          - Four timers implemented as modulus down-counters with
**            independent time-out periods.
**          - Time-out periods selectable between 1 and 224 bus clock
**            cycles. Time-out equals m*n bus clock cycles with
**            1 <= m >= 256 and 1 <= n >= 65536.
**          - Timers that can be enabled individually.
**          - Four time-out interrupts.
**          - Four time-out trigger output signals available to trigger
**            peripheral modules.
**          - Start of timer channels can be aligned to each other.
**     Settings  :
**          Component name                                 : TimeStamp
**          PIT device                                     : PIT
**          Settings                                       : 
**            Clock settings                               : 
**              Micro Timer 0 load register                : 39
**              Micro Timer 1 load register                : 199
**              Frequency of the Micro Timer 0             : 1 MHz
**              Frequency of the Micro Timer 1             : 200 kHz
**            Stop in wait mode                            : no
**            Stop in freeze mode                          : no
**          Channels                                       : 3
**            Channel                                      : 
**              Device                                     : PIT2
**              Enable Timer                               : yes
**              Timer is connected to                      : Micro Timer 0
**              Timer Load register                        : FFFF
**              Frequency of Timer                         : 15.258 Hz
**              Interrupt                                  : 
**                Timer out interrupt                      : Enabled
**                Interrupt                                : Vpit2
**                Priority                                 : 4
**                ISR name                                 : TimeStampInc
**            Channel                                      : 
**              Device                                     : PIT1
**              Enable Timer                               : yes
**              Timer is connected to                      : Micro Timer 1
**              Timer Load register                        : 19999
**              Frequency of Timer                         : 10 Hz
**              Interrupt                                  : 
**                Timer out interrupt                      : Enabled
**                Interrupt                                : Vpit1
**                Priority                                 : 4
**                ISR name                                 : PIT1_100MS
**            Channel                                      : 
**              Device                                     : PIT0
**              Enable Timer                               : no
**              Timer is connected to                      : Micro Timer 1
**              Timer Load register                        : 99
**              Frequency of Timer                         : 2 kHz
**              Interrupt                                  : 
**                Timer out interrupt                      : Disabled
**                Interrupt                                : Vpit0
**                Priority                                 : 4
**                ISR name                                 : 
**          Initialization                                 : 
**            Call Init method                             : yes
**            PIT periphery                                : Enabled
**     Contents  :
**         Init - void TimeStamp_Init(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE TimeStamp. */

#include "TimeStamp.h"

/*
** ###################################################################
**
**  The interrupt service routine(s) must be implemented
**  by user in one of the following user modules.
**
**  If the "Generate ISR" option is enabled, Processor Expert generates
**  ISR templates in the CPU event module.
**
**  User modules:
**      Project.c
**      Events.c
**
** ###################################################################
#pragma CODE_SEG __NEAR_SEG NON_BANKED
ISR(TimeStampInc)
{
  // NOTE: The routine should include the following actions to obtain
  //       correct functionality of the hardware.
  //
  //       Timer n flag (PTFn bit in Flag Register PITTF) must be set to 1 to clear the interrupt request.
  //       Example: PITTF_PTFn = 1;
}
ISR(PIT1_100MS)
{
  // NOTE: The routine should include the following actions to obtain
  //       correct functionality of the hardware.
  //
  //       Timer n flag (PTFn bit in Flag Register PITTF) must be set to 1 to clear the interrupt request.
  //       Example: PITTF_PTFn = 1;
}
#pragma CODE_SEG DEFAULT
*/

/*
** ===================================================================
**     Method      :  TimeStamp_Init (component Init_PIT)
**
**     Description :
**         This method initializes registers of the TIM module
**         according to this Peripheral Initialization settings. Call
**         this method in user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void TimeStamp_Init(void)
{
  /* PITCFLMT: PITE=0 */
  clrReg8Bits(PITCFLMT, 0x80U);         
  /* PITMTLD0: PMTLD7=0,PMTLD6=0,PMTLD5=1,PMTLD4=0,PMTLD3=0,PMTLD2=1,PMTLD1=1,PMTLD0=1 */
  setReg8(PITMTLD0, 0x27U);             
  /* PITMTLD1: PMTLD7=1,PMTLD6=1,PMTLD5=0,PMTLD4=0,PMTLD3=0,PMTLD2=1,PMTLD1=1,PMTLD0=1 */
  setReg8(PITMTLD1, 0xC7U);             
  /* PITLD2: PLD15=1,PLD14=1,PLD13=1,PLD12=1,PLD11=1,PLD10=1,PLD9=1,PLD8=1,PLD7=1,PLD6=1,PLD5=1,PLD4=1,PLD3=1,PLD2=1,PLD1=1,PLD0=1 */
  setReg16(PITLD2, 0xFFFFU);            
  /* PITLD1: PLD15=0,PLD14=1,PLD13=0,PLD12=0,PLD11=1,PLD10=1,PLD9=1,PLD8=0,PLD7=0,PLD6=0,PLD5=0,PLD4=1,PLD3=1,PLD2=1,PLD1=1,PLD0=1 */
  setReg16(PITLD1, 0x4E1FU);            
  /* PITLD0: PLD15=0,PLD14=0,PLD13=0,PLD12=0,PLD11=0,PLD10=0,PLD9=0,PLD8=0,PLD7=0,PLD6=1,PLD5=1,PLD4=0,PLD3=0,PLD2=0,PLD1=1,PLD0=1 */
  setReg16(PITLD0, 0x63U);              
  /* PITMUX: PMUX7=0,PMUX6=0,PMUX5=0,PMUX4=0,PMUX3=0,PMUX2=0,PMUX1=1,PMUX0=1 */
  setReg8(PITMUX, 0x03U);               
  /* PITCE: PCE7=0,PCE6=0,PCE5=0,PCE4=0,PCE3=0,PCE2=1,PCE1=1,PCE0=0 */
  setReg8(PITCE, 0x06U);                
  /* PITTF: PTF7=0,PTF6=0,PTF5=0,PTF4=0,PTF3=0,PTF2=1,PTF1=1,PTF0=1 */
  setReg8(PITTF, 0x07U);                
  /* PITINTE: PINTE7=0,PINTE6=0,PINTE5=0,PINTE4=0,PINTE3=0,PINTE2=1,PINTE1=1,PINTE0=0 */
  setReg8(PITINTE, 0x06U);              
  /* PITCFLMT: PITE=1,PITSWAI=0,PITFRZ=0,??=0,??=0,??=0,PFLMT1=0,PFLMT0=0 */
  setReg8(PITCFLMT, 0x80U);             
}

/* END TimeStamp. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
